import assert from "node:assert/strict";
import test from "node:test";
import {applyModerationActionForCaller} from "../src/moderation_mutation";
import type {ModerationTransactionExtension} from "../src/moderation_transaction_extension";

type Data = Record<string, unknown>;
class FakeDb {
  data = new Map<string, Data>(); fail = new Set<string>(); directFailOnce = new Set<string>(); transactionFailOnce = new Set<string>(); beforeTransaction: (() => void) | undefined;
  collection(id: string) { return new Col(this, id); }
  async runTransaction<T>(work: (tx: Tx) => Promise<T>): Promise<T> { this.beforeTransaction?.(); this.beforeTransaction = undefined; const tx = new Tx(this); const result = await work(tx); tx.commit(); return result; }
}
class Col { constructor(readonly db: FakeDb, readonly path: string) {} doc(id: string) { return new Doc(this.db, `${this.path}/${id}`); } where(field: string, _op: string, value: unknown) { return new Query(this.db, this.path, field, value); } }
class Doc { constructor(readonly db: FakeDb, readonly path: string) {} collection(id: string) { return new Col(this.db, `${this.path}/${id}`); } async get() { return snap(this.db.data.get(this.path)); } async set(value: Data, options?: {merge?: boolean}) { if (this.db.directFailOnce.delete(this.path)) throw new Error(`injected:${this.path}`); if (this.db.fail.has(this.path)) throw new Error(`injected:${this.path}`); this.db.data.set(this.path, options?.merge ? {...(this.db.data.get(this.path) ?? {}), ...value} : value); } }
class Query { constructor(readonly db: FakeDb, readonly path: string, readonly field: string, readonly value: unknown) {} }
class Tx {
  staged = new Map<string, Data | null>(); constructor(readonly db: FakeDb) {}
  async get(target: Doc | Query): Promise<any> { if (target instanceof Query) { const prefix = `${target.path}/`; const docs = [...this.db.data.entries()].filter(([path, data]) => path.startsWith(prefix) && !path.slice(prefix.length).includes("/") && data[target.field] === target.value).map(([path, data]) => ({ref: new Doc(this.db, path), ...snap(data)})); return {docs}; } return snap(this.staged.has(target.path) ? this.staged.get(target.path) ?? undefined : this.db.data.get(target.path)); }
  update(ref: Doc, value: Data) { this.stage(ref.path, {...(this.db.data.get(ref.path) ?? {}), ...value}); }
  set(ref: Doc, value: Data, options?: {merge?: boolean}) { this.stage(ref.path, options?.merge ? {...(this.db.data.get(ref.path) ?? {}), ...value} : value); }
  create(ref: Doc, value: Data) { if (this.db.data.has(ref.path)) throw new Error("exists"); this.stage(ref.path, value); }
  stage(path: string, value: Data) { if (this.db.transactionFailOnce.delete(path) || this.db.fail.has(path)) throw new Error(`injected:${path}`); this.staged.set(path, value); }
  commit() { for (const [path, value] of this.staged) { if (value === null) this.db.data.delete(path); else this.db.data.set(path, value); } }
}
function snap(data: Data | undefined) { return {exists: data !== undefined, data: () => data}; }
const db = () => new FakeDb() as unknown as import("firebase-admin/firestore").Firestore & {data: Map<string, Data>; fail: Set<string>; directFailOnce: Set<string>; transactionFailOnce: Set<string>; beforeTransaction: (() => void) | undefined};
const admin = {uid: "admin-a", customClaims: {admin: true}};
const request = (target: Data, action: string, id = "550e8400-e29b-41d4-a716-446655440000") => ({requestId: id, target, action, reason: "moderation reason"});
const machineId = "machine_v2_station_east"; const productId = "product_tea_green";
function seed(store: ReturnType<typeof db>, path: string, value: Data) { store.data.set(path, value); }
function count(store: ReturnType<typeof db>, prefix: string) { return [...store.data.keys()].filter((path) => path.startsWith(prefix)).length; }

test("machine mutation updates all indexes, audit and dedupe atomically", async () => {
  const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, `vending_machines/${machineId}`, {status: "active"}); seed(store, `machine_product_index/${machineId}_a`, {machineId, isActive: true}); seed(store, `machine_product_index/${machineId}_b`, {machineId, isActive: true}); seed(store, `vending_machines/${machineId}/products/${productId}`, {isActive: true});
  const result = await applyModerationActionForCaller(store, admin, request({targetType: "machine", machineId}, "underReview"));
  assert.equal(result.nextStatus, "underReview"); assert.equal(store.data.get(`vending_machines/${machineId}`)?.status, "underReview"); assert.equal(store.data.get(`${`machine_product_index/${machineId}_a`}`)?.isActive, false); assert.equal(store.data.get(`vending_machines/${machineId}/products/${productId}`)?.isActive, true); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1);
});

test("machine extension stages its private record atomically after validation", async () => {
  const store = db(); const calls: string[] = []; const extension: ModerationTransactionExtension = {
    phase: "mutation", metadata: {kind: "test"},
    validate: (context) => { calls.push("validate"); assert.equal(context.phase, "mutation"); assert.equal(context.previousStatus, "active"); assert.equal(context.nextStatus, "underReview"); },
    stage: (context, port) => { calls.push("stage"); assert.equal(context.target.targetType, "machine"); port.setPrivateRecord("machine-stage", {status: context.nextStatus!}); },
  };
  seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, `vending_machines/${machineId}`, {status: "active"}); seed(store, `machine_product_index/${machineId}_a`, {machineId, isActive: true});
  const input = request({targetType: "machine", machineId}, "underReview", "550e8400-e29b-41d4-a716-446655440020");
  const result = await applyModerationActionForCaller(store, admin, input, undefined, extension);
  assert.equal(result.nextStatus, "underReview"); assert.deepEqual(calls, ["validate", "stage"]); assert.equal(store.data.get(`vending_machines/${machineId}`)?.status, "underReview"); assert.equal(store.data.get(`machine_product_index/${machineId}_a`)?.isActive, false); assert.deepEqual(store.data.get("moderation_private_transaction_extensions/machine-stage"), {status: "underReview"}); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); assert.equal("moderatorUid" in result, false);
});

test("machine extension failures roll back staged target, index, audit and dedupe writes", async () => {
  const prepare = () => { const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, `vending_machines/${machineId}`, {status: "active"}); seed(store, `machine_product_index/${machineId}_a`, {machineId, isActive: true}); return store; };
  const input = request({targetType: "machine", machineId}, "underReview", "550e8400-e29b-41d4-a716-446655440021");
  const stageThrowStore = prepare(); const stageThrow: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: () => { throw new Error("stage-failure"); }};
  await assert.rejects(() => applyModerationActionForCaller(stageThrowStore, admin, input, undefined, stageThrow));
  for (const store of [stageThrowStore]) { assert.equal(store.data.get(`vending_machines/${machineId}`)?.status, "active"); assert.equal(store.data.get(`machine_product_index/${machineId}_a`)?.isActive, true); assert.equal(count(store, "moderation_private_transaction_extensions/"), 0); assert.equal(count(store, "moderation_private_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0); }
  const portFailStore = prepare(); portFailStore.fail.add("moderation_private_transaction_extensions/machine-stage"); const portWrite: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: (_context, port) => port.setPrivateRecord("machine-stage", {value: true})};
  await assert.rejects(() => applyModerationActionForCaller(portFailStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440022"}, undefined, portWrite));
  assert.equal(portFailStore.data.get(`vending_machines/${machineId}`)?.status, "active"); assert.equal(portFailStore.data.get(`machine_product_index/${machineId}_a`)?.isActive, true); assert.equal(count(portFailStore, "moderation_private_transaction_extensions/"), 0); assert.equal(count(portFailStore, "moderation_private_audit/"), 0); assert.equal(count(portFailStore, "request_deduplication/"), 0);
});

test("machine extension is skipped for validation failures, rejected transitions and dedupe replays", async () => {
  const store = db(); let validates = 0; let stages = 0; const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { validates++; }, stage: () => { stages++; }};
  seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, `vending_machines/${machineId}`, {status: "underReview"});
  await assert.rejects(() => applyModerationActionForCaller(store, admin, request({targetType: "machine", machineId}, "underReview", "550e8400-e29b-41d4-a716-446655440023"), undefined, extension)); assert.equal(validates, 0); assert.equal(stages, 0);
  store.data.set(`vending_machines/${machineId}`, {status: "active"}); const validationFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { throw new Error("validate-failure"); }, stage: () => { stages++; }};
  await assert.rejects(() => applyModerationActionForCaller(store, admin, request({targetType: "machine", machineId}, "underReview", "550e8400-e29b-41d4-a716-446655440024"), undefined, validationFailure)); assert.equal(stages, 0); assert.equal(store.data.get(`vending_machines/${machineId}`)?.status, "active"); assert.equal(count(store, "moderation_private_audit/"), 0);
  const replayInput = request({targetType: "machine", machineId}, "underReview", "550e8400-e29b-41d4-a716-446655440025"); await applyModerationActionForCaller(store, admin, replayInput, undefined, extension); const audits = count(store, "moderation_private_audit/"); const extensionWrites = count(store, "moderation_private_transaction_extensions/"); await applyModerationActionForCaller(store, admin, replayInput, undefined, extension); assert.equal(validates, 1); assert.equal(stages, 1); assert.equal(count(store, "moderation_private_audit/"), audits); assert.equal(count(store, "moderation_private_transaction_extensions/"), extensionWrites);
});

test("machine extension is skipped when the transaction reread observes a stale transition", async () => {
  const store = db(); let validates = 0; let stages = 0; const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { validates++; }, stage: () => { stages++; }};
  seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, `vending_machines/${machineId}`, {status: "active"}); seed(store, `machine_product_index/${machineId}_a`, {machineId, isActive: true});
  store.beforeTransaction = () => seed(store, `vending_machines/${machineId}`, {status: "underReview"});
  await assert.rejects(() => applyModerationActionForCaller(store, admin, request({targetType: "machine", machineId}, "underReview", "550e8400-e29b-41d4-a716-446655440026"), undefined, extension));
  assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(store.data.get(`vending_machines/${machineId}`)?.status, "underReview"); assert.equal(store.data.get(`machine_product_index/${machineId}_a`)?.isActive, true); assert.equal(count(store, "moderation_private_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0);
});

test("product extension validates and stages the machine relation atomically without changing the master", async () => {
  const store = db(); const calls: string[] = []; const relationPath = `vending_machines/${machineId}/products/${productId}`; const indexPath = `machine_product_index/${machineId}_${productId}`; const masterPath = `products/${productId}`;
  const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: (context) => { calls.push("validate"); assert.equal(context.phase, "mutation"); assert.equal(context.target.targetType, "product"); assert.equal(context.previousStatus, "active"); assert.equal(context.nextStatus, "inactive"); }, stage: (context, port) => { calls.push("stage"); port.setPrivateRecord("product-stage", {status: context.nextStatus!}); }};
  seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, relationPath, {isActive: true}); seed(store, indexPath, {isActive: true, machineId, productId}); seed(store, masterPath, {isActive: true, master: true});
  const result = await applyModerationActionForCaller(store, admin, request({targetType: "product", machineId, productId}, "inactive", "550e8400-e29b-41d4-a716-446655440030"), undefined, extension);
  assert.equal(result.nextStatus, "inactive"); assert.deepEqual(calls, ["validate", "stage"]); assert.equal(store.data.get(relationPath)?.isActive, false); assert.equal(store.data.get(indexPath)?.isActive, false); assert.deepEqual(store.data.get(masterPath), {isActive: true, master: true}); assert.deepEqual(store.data.get("moderation_private_transaction_extensions/product-stage"), {status: "inactive"}); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); assert.equal("moderatorUid" in result, false);
});

test("product extension failures roll back relation, index, extension, audit and dedupe", async () => {
  const relationPath = `vending_machines/${machineId}/products/${productId}`; const indexPath = `machine_product_index/${machineId}_${productId}`;
  const prepare = () => { const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, relationPath, {isActive: true}); seed(store, indexPath, {isActive: true, machineId, productId}); return store; };
  const input = request({targetType: "product", machineId, productId}, "inactive", "550e8400-e29b-41d4-a716-446655440031");
  const validationStore = prepare(); let validationStages = 0; const validationFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { throw new Error("validate-failure"); }, stage: () => { validationStages++; }};
  await assert.rejects(() => applyModerationActionForCaller(validationStore, admin, input, undefined, validationFailure)); assert.equal(validationStages, 0); assert.equal(validationStore.data.get(relationPath)?.isActive, true); assert.equal(validationStore.data.get(indexPath)?.isActive, true); assert.equal(count(validationStore, "moderation_private_audit/"), 0); assert.equal(count(validationStore, "request_deduplication/"), 0);
  const stageStore = prepare(); const stageFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: () => { throw new Error("stage-failure"); }};
  await assert.rejects(() => applyModerationActionForCaller(stageStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440032"}, undefined, stageFailure)); assert.equal(stageStore.data.get(relationPath)?.isActive, true); assert.equal(stageStore.data.get(indexPath)?.isActive, true); assert.equal(count(stageStore, "moderation_private_transaction_extensions/"), 0); assert.equal(count(stageStore, "moderation_private_audit/"), 0); assert.equal(count(stageStore, "request_deduplication/"), 0);
  const portStore = prepare(); portStore.fail.add("moderation_private_transaction_extensions/product-stage"); const portFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: (_context, port) => port.setPrivateRecord("product-stage", {value: true})};
  await assert.rejects(() => applyModerationActionForCaller(portStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440033"}, undefined, portFailure)); assert.equal(portStore.data.get(relationPath)?.isActive, true); assert.equal(portStore.data.get(indexPath)?.isActive, true); assert.equal(count(portStore, "moderation_private_transaction_extensions/"), 0); assert.equal(count(portStore, "moderation_private_audit/"), 0); assert.equal(count(portStore, "request_deduplication/"), 0);
});

test("product extension is skipped for inconsistent relations, stale transaction reads and dedupe replays", async () => {
  const relationPath = `vending_machines/${machineId}/products/${productId}`; const indexPath = `machine_product_index/${machineId}_${productId}`; let validates = 0; let stages = 0; const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { validates++; }, stage: () => { stages++; }};
  const inconsistent = db(); seed(inconsistent, "users/admin-a", {accountStatus: "active"}); seed(inconsistent, relationPath, {isActive: true}); await assert.rejects(() => applyModerationActionForCaller(inconsistent, admin, request({targetType: "product", machineId, productId}, "inactive", "550e8400-e29b-41d4-a716-446655440034"), undefined, extension)); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(count(inconsistent, "moderation_private_audit/"), 0); assert.equal(count(inconsistent, "request_deduplication/"), 0);
  const inactive = db(); seed(inactive, "users/admin-a", {accountStatus: "active"}); seed(inactive, relationPath, {isActive: false}); seed(inactive, indexPath, {isActive: true, machineId, productId}); await assert.rejects(() => applyModerationActionForCaller(inactive, admin, request({targetType: "product", machineId, productId}, "inactive", "550e8400-e29b-41d4-a716-446655440037"), undefined, extension)); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(count(inactive, "moderation_private_audit/"), 0); assert.equal(count(inactive, "request_deduplication/"), 0);
  const stale = db(); seed(stale, "users/admin-a", {accountStatus: "active"}); seed(stale, relationPath, {isActive: true}); seed(stale, indexPath, {isActive: true, machineId, productId}); stale.beforeTransaction = () => seed(stale, relationPath, {isActive: false}); await assert.rejects(() => applyModerationActionForCaller(stale, admin, request({targetType: "product", machineId, productId}, "inactive", "550e8400-e29b-41d4-a716-446655440035"), undefined, extension)); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(stale.data.get(indexPath)?.isActive, true);
  const replay = db(); seed(replay, "users/admin-a", {accountStatus: "active"}); seed(replay, relationPath, {isActive: true}); seed(replay, indexPath, {isActive: true, machineId, productId}); const input = request({targetType: "product", machineId, productId}, "inactive", "550e8400-e29b-41d4-a716-446655440036"); await applyModerationActionForCaller(replay, admin, input, undefined, extension); const audits = count(replay, "moderation_private_audit/"); await applyModerationActionForCaller(replay, admin, input, undefined, extension); assert.equal(validates, 1); assert.equal(stages, 1); assert.equal(count(replay, "moderation_private_audit/"), audits); assert.equal(count(replay, "request_deduplication/"), 1);
});

test("user extension validates and stages account status atomically without Auth changes", async () => {
  const store = db(); const target = "target-user"; const calls: string[] = []; const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: (context) => { calls.push("validate"); assert.equal(context.phase, "mutation"); assert.equal(context.target.targetType, "user"); assert.equal(context.previousStatus, "active"); assert.equal(context.nextStatus, "restricted"); }, stage: (context, port) => { calls.push("stage"); port.setPrivateRecord("user-stage", {status: context.nextStatus!}); }};
  seed(store, "users/admin-a", {accountStatus: "active", customClaims: {admin: true}}); seed(store, `users/${target}`, {accountStatus: "active", email: "unchanged@example.test", profile: "unchanged"});
  const result = await applyModerationActionForCaller(store, admin, request({targetType: "user", targetUserId: target}, "restricted", "550e8400-e29b-41d4-a716-446655440040"), undefined, extension);
  assert.equal(result.nextStatus, "restricted"); assert.deepEqual(calls, ["validate", "stage"]); assert.equal(store.data.get(`users/${target}`)?.accountStatus, "restricted"); assert.equal(store.data.get(`users/${target}`)?.email, "unchanged@example.test"); assert.equal(store.data.get("users/admin-a")?.customClaims instanceof Object, true); assert.deepEqual(store.data.get("moderation_private_transaction_extensions/user-stage"), {status: "restricted"}); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); assert.equal("moderatorUid" in result, false);
});

test("user moderation preserves supported transitions with the direct no-op extension", async () => {
  const cases: Array<[string, string]> = [["active", "suspended"], ["restricted", "active"], ["suspended", "active"]];
  for (const [index, [current, action]] of cases.entries()) { const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, "users/target-user", {accountStatus: current}); const result = await applyModerationActionForCaller(store, admin, request({targetType: "user", targetUserId: "target-user"}, action, `550e8400-e29b-41d4-a716-44665544004${index}`)); assert.equal(result.nextStatus, action); assert.equal(store.data.get("users/target-user")?.accountStatus, action); }
});

test("user extension failures roll back account status, extension, audit and dedupe", async () => {
  const target = "target-user"; const userPath = `users/${target}`; const prepare = () => { const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, userPath, {accountStatus: "active"}); return store; }; const input = request({targetType: "user", targetUserId: target}, "restricted", "550e8400-e29b-41d4-a716-446655440044");
  const validationStore = prepare(); let validationStages = 0; const validationFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { throw new Error("validate-failure"); }, stage: () => { validationStages++; }};
  await assert.rejects(() => applyModerationActionForCaller(validationStore, admin, input, undefined, validationFailure)); assert.equal(validationStages, 0); assert.equal(validationStore.data.get(userPath)?.accountStatus, "active"); assert.equal(count(validationStore, "moderation_private_audit/"), 0); assert.equal(count(validationStore, "request_deduplication/"), 0);
  const stageStore = prepare(); const stageFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: () => { throw new Error("stage-failure"); }};
  await assert.rejects(() => applyModerationActionForCaller(stageStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440045"}, undefined, stageFailure)); assert.equal(stageStore.data.get(userPath)?.accountStatus, "active"); assert.equal(count(stageStore, "moderation_private_transaction_extensions/"), 0); assert.equal(count(stageStore, "moderation_private_audit/"), 0); assert.equal(count(stageStore, "request_deduplication/"), 0);
  const portStore = prepare(); portStore.fail.add("moderation_private_transaction_extensions/user-stage"); const portFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: (_context, port) => port.setPrivateRecord("user-stage", {value: true})};
  await assert.rejects(() => applyModerationActionForCaller(portStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440046"}, undefined, portFailure)); assert.equal(portStore.data.get(userPath)?.accountStatus, "active"); assert.equal(count(portStore, "moderation_private_transaction_extensions/"), 0); assert.equal(count(portStore, "moderation_private_audit/"), 0); assert.equal(count(portStore, "request_deduplication/"), 0);
});

test("user extension is skipped for invalid transitions, stale reads and dedupe replays", async () => {
  const target = "target-user"; const userPath = `users/${target}`; let validates = 0; let stages = 0; const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { validates++; }, stage: () => { stages++; }};
  const invalid = db(); seed(invalid, "users/admin-a", {accountStatus: "active"}); seed(invalid, userPath, {accountStatus: "active"}); await assert.rejects(() => applyModerationActionForCaller(invalid, admin, request({targetType: "user", targetUserId: target}, "active", "550e8400-e29b-41d4-a716-446655440047"), undefined, extension)); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(count(invalid, "moderation_private_audit/"), 0); assert.equal(count(invalid, "request_deduplication/"), 0);
  const stale = db(); seed(stale, "users/admin-a", {accountStatus: "active"}); seed(stale, userPath, {accountStatus: "active"}); stale.beforeTransaction = () => seed(stale, userPath, {accountStatus: "restricted"}); await assert.rejects(() => applyModerationActionForCaller(stale, admin, request({targetType: "user", targetUserId: target}, "restricted", "550e8400-e29b-41d4-a716-446655440048"), undefined, extension)); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(stale.data.get(userPath)?.accountStatus, "restricted");
  const replay = db(); seed(replay, "users/admin-a", {accountStatus: "active"}); seed(replay, userPath, {accountStatus: "active"}); const input = request({targetType: "user", targetUserId: target}, "restricted", "550e8400-e29b-41d4-a716-446655440049"); await applyModerationActionForCaller(replay, admin, input, undefined, extension); const audits = count(replay, "moderation_private_audit/"); await applyModerationActionForCaller(replay, admin, input, undefined, extension); assert.equal(validates, 1); assert.equal(stages, 1); assert.equal(count(replay, "moderation_private_audit/"), audits); assert.equal(count(replay, "request_deduplication/"), 1);
});

test("product and user mutations preserve master/Auth boundaries and dedupe replay", async () => {
  const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, "users/target", {accountStatus: "active"}); seed(store, `vending_machines/${machineId}/products/${productId}`, {isActive: true}); seed(store, `machine_product_index/${machineId}_${productId}`, {isActive: true}); seed(store, `products/${productId}`, {isActive: true, master: true});
  await applyModerationActionForCaller(store, admin, request({targetType: "product", machineId, productId}, "inactive"));
  assert.equal(store.data.get(`vending_machines/${machineId}/products/${productId}`)?.isActive, false); assert.equal(store.data.get(`machine_product_index/${machineId}_${productId}`)?.isActive, false); assert.equal(store.data.get(`products/${productId}`)?.isActive, true);
  const userInput = request({targetType: "user", targetUserId: "target"}, "restricted", "550e8400-e29b-41d4-a716-446655440001"); await applyModerationActionForCaller(store, admin, userInput); const audits = count(store, "moderation_private_audit/"); await applyModerationActionForCaller(store, admin, userInput); assert.equal(store.data.get("users/target")?.accountStatus, "restricted"); assert.equal(count(store, "moderation_private_audit/"), audits);
});

test("missing, stale and injected failures leave no partial target, audit or dedupe writes", async () => {
  const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, `vending_machines/${machineId}`, {status: "underReview"}); seed(store, `machine_product_index/${machineId}_a`, {machineId, isActive: true});
  await assert.rejects(() => applyModerationActionForCaller(store, admin, request({targetType: "machine", machineId}, "underReview"))); assert.equal(count(store, "moderation_private_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0);
  store.data.set(`vending_machines/${machineId}`, {status: "active"}); store.fail.add(`machine_product_index/${machineId}_a`);
  await assert.rejects(() => applyModerationActionForCaller(store, admin, request({targetType: "machine", machineId}, "underReview", "550e8400-e29b-41d4-a716-446655440002"))); assert.equal(store.data.get(`vending_machines/${machineId}`)?.status, "active"); assert.equal(count(store, "moderation_private_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0);
});

test("photo hidden extension validates and stages public/private changes atomically without Storage access", async () => {
  const store = db(); const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; const calls: string[] = []; let deletes = 0; const bucket = {file: (_path: string) => ({delete: async () => { deletes++; }})};
  const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: (context) => { calls.push("validate"); assert.equal(context.phase, "mutation"); assert.equal(context.target.targetType, "photo"); assert.equal(context.previousStatus, "active"); assert.equal(context.nextStatus, "hidden"); }, stage: (context, port) => { calls.push("stage"); port.setPrivateRecord("photo-hidden-stage", {status: context.nextStatus!}); }};
  seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active", createdAt: 1}); seed(store, privatePath, {uploadedBy: "private-actor", recognition: {provider: "private"}});
  const result = await applyModerationActionForCaller(store, admin, request({targetType: "photo", machineId, photoId: photo}, "hidden", "550e8400-e29b-41d4-a716-446655440050"), bucket, extension);
  assert.equal(result.nextStatus, "hidden"); assert.deepEqual(calls, ["validate", "stage"]); assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "hidden"); assert.equal(store.data.get(privatePath)?.uploadedBy, "private-actor"); assert.deepEqual(store.data.get("moderation_private_transaction_extensions/photo-hidden-stage"), {status: "hidden"}); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); assert.equal(deletes, 0); for (const key of ["uploadedBy", "actorUid", "moderatorUid", "storagePath", "deletionPending", "privateMetadata"]) assert.equal(key in (store.data.get(publicPath) ?? {}), false); assert.equal("moderatorUid" in result, false);
});

test("photo hidden extension failures roll back public/private changes without Storage access", async () => {
  const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; const prepare = () => { const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active"}); seed(store, privatePath, {uploadedBy: "private-actor"}); return store; }; const input = request({targetType: "photo", machineId, photoId: photo}, "hidden", "550e8400-e29b-41d4-a716-446655440051");
  const validationStore = prepare(); let validationStages = 0; const validationFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { throw new Error("validate-failure"); }, stage: () => { validationStages++; }};
  await assert.rejects(() => applyModerationActionForCaller(validationStore, admin, input, undefined, validationFailure)); assert.equal(validationStages, 0); assert.equal(validationStore.data.get(publicPath)?.status, "active"); assert.equal(validationStore.data.get(privatePath)?.moderationStatus, undefined); assert.equal(count(validationStore, "moderation_private_audit/"), 0); assert.equal(count(validationStore, "request_deduplication/"), 0);
  const stageStore = prepare(); const stageFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: () => { throw new Error("stage-failure"); }};
  await assert.rejects(() => applyModerationActionForCaller(stageStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440052"}, undefined, stageFailure)); assert.equal(stageStore.data.get(publicPath)?.status, "active"); assert.equal(stageStore.data.get(privatePath)?.moderationStatus, undefined); assert.equal(count(stageStore, "moderation_private_transaction_extensions/"), 0); assert.equal(count(stageStore, "moderation_private_audit/"), 0); assert.equal(count(stageStore, "request_deduplication/"), 0);
  const portStore = prepare(); portStore.fail.add("moderation_private_transaction_extensions/photo-hidden-stage"); const portFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: (_context, port) => port.setPrivateRecord("photo-hidden-stage", {value: true})};
  await assert.rejects(() => applyModerationActionForCaller(portStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440053"}, undefined, portFailure)); assert.equal(portStore.data.get(publicPath)?.status, "active"); assert.equal(portStore.data.get(privatePath)?.moderationStatus, undefined); assert.equal(count(portStore, "moderation_private_transaction_extensions/"), 0); assert.equal(count(portStore, "moderation_private_audit/"), 0); assert.equal(count(portStore, "request_deduplication/"), 0);
});

test("photo hidden extension is skipped for invalid transitions, stale reads and dedupe replays", async () => {
  const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; let validates = 0; let stages = 0; const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { validates++; }, stage: () => { stages++; }};
  const invalid = db(); seed(invalid, "users/admin-a", {accountStatus: "active"}); seed(invalid, publicPath, {status: "inactive"}); seed(invalid, privatePath, {uploadedBy: "private"}); await assert.rejects(() => applyModerationActionForCaller(invalid, admin, request({targetType: "photo", machineId, photoId: photo}, "hidden", "550e8400-e29b-41d4-a716-446655440054"), undefined, extension)); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(count(invalid, "moderation_private_audit/"), 0); assert.equal(count(invalid, "request_deduplication/"), 0);
  const stale = db(); seed(stale, "users/admin-a", {accountStatus: "active"}); seed(stale, publicPath, {status: "active"}); seed(stale, privatePath, {uploadedBy: "private"}); stale.beforeTransaction = () => seed(stale, publicPath, {status: "inactive"}); await assert.rejects(() => applyModerationActionForCaller(stale, admin, request({targetType: "photo", machineId, photoId: photo}, "hidden", "550e8400-e29b-41d4-a716-446655440055"), undefined, extension)); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(stale.data.get(privatePath)?.moderationStatus, undefined);
  const replay = db(); seed(replay, "users/admin-a", {accountStatus: "active"}); seed(replay, publicPath, {status: "active"}); seed(replay, privatePath, {uploadedBy: "private"}); const input = request({targetType: "photo", machineId, photoId: photo}, "hidden", "550e8400-e29b-41d4-a716-446655440056"); await applyModerationActionForCaller(replay, admin, input, undefined, extension); const audits = count(replay, "moderation_private_audit/"); await applyModerationActionForCaller(replay, admin, input, undefined, extension); assert.equal(validates, 1); assert.equal(stages, 1); assert.equal(count(replay, "moderation_private_audit/"), audits); assert.equal(count(replay, "request_deduplication/"), 1);
});

test("photo deleted phase 1 validates and stages atomically before the unchanged Storage/finalize workflow", async () => {
  const store = db(); const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; const calls: string[] = []; let deletes = 0;
  const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: (context) => { calls.push("validate"); assert.equal(context.phase, "mutation"); assert.equal(context.target.targetType, "photo"); assert.equal(context.action, "deleted"); assert.equal(context.previousStatus, "active"); assert.equal(context.nextStatus, "deleted"); }, stage: (context, port) => { calls.push("stage"); port.setPrivateRecord("photo-deleted-stage", {status: context.nextStatus!}); }};
  const bucket = {file: (_path: string) => ({delete: async () => { deletes++; assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "deletionPending"); assert.equal(count(store, "moderation_private_transaction_extensions/"), 1); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); }})};
  seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active", createdAt: 1}); seed(store, privatePath, {uploadedBy: "private-actor"});
  const result = await applyModerationActionForCaller(store, admin, request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440060"), bucket, extension);
  assert.equal(result.nextStatus, "deleted"); assert.deepEqual(calls, ["validate", "stage"]); assert.equal(deletes, 1); assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "deleted"); assert.equal(store.data.get(privatePath)?.uploadedBy, "private-actor"); assert.deepEqual(store.data.get("moderation_private_transaction_extensions/photo-deleted-stage"), {status: "deleted"}); for (const key of ["uploadedBy", "actorUid", "moderatorUid", "storagePath", "deletionPending", "deletionCompletedAt", "extensionMetadata"]) assert.equal(key in (store.data.get(publicPath) ?? {}), false); assert.equal("moderatorUid" in result, false);
});

test("photo deleted phase 1 extension failures roll back before Storage", async () => {
  const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; const prepare = () => { const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active"}); seed(store, privatePath, {uploadedBy: "private"}); return store; }; const input = request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440061");
  const assertRollback = (store: ReturnType<typeof db>) => { assert.equal(store.data.get(publicPath)?.status, "active"); assert.equal(store.data.get(privatePath)?.moderationStatus, undefined); assert.equal(count(store, "moderation_private_transaction_extensions/"), 0); assert.equal(count(store, "moderation_private_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0); };
  const validationStore = prepare(); let validationStages = 0; let validationDeletes = 0; const validationFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { throw new Error("validate-failure"); }, stage: () => { validationStages++; }};
  await assert.rejects(() => applyModerationActionForCaller(validationStore, admin, input, {file: () => ({delete: async () => { validationDeletes++; }})}, validationFailure)); assert.equal(validationStages, 0); assert.equal(validationDeletes, 0); assertRollback(validationStore);
  const stageStore = prepare(); let stageDeletes = 0; const stageFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: () => { throw new Error("stage-failure"); }};
  await assert.rejects(() => applyModerationActionForCaller(stageStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440062"}, {file: () => ({delete: async () => { stageDeletes++; }})}, stageFailure)); assert.equal(stageDeletes, 0); assertRollback(stageStore);
  const portStore = prepare(); let portDeletes = 0; portStore.fail.add("moderation_private_transaction_extensions/photo-deleted-stage"); const portFailure: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: (_context, port) => port.setPrivateRecord("photo-deleted-stage", {value: true})};
  await assert.rejects(() => applyModerationActionForCaller(portStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440063"}, {file: () => ({delete: async () => { portDeletes++; }})}, portFailure)); assert.equal(portDeletes, 0); assertRollback(portStore);
});

test("photo deleted skips the extension for invalid/stale phase 1 and replays only Storage/finalize after commit", async () => {
  const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; let validates = 0; let stages = 0; const extension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { validates++; }, stage: () => { stages++; }};
  const invalid = db(); seed(invalid, "users/admin-a", {accountStatus: "active"}); seed(invalid, publicPath, {status: "deleted"}); seed(invalid, privatePath, {uploadedBy: "private"}); let invalidDeletes = 0; await assert.rejects(() => applyModerationActionForCaller(invalid, admin, request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440064"), {file: () => ({delete: async () => { invalidDeletes++; }})}, extension)); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(invalidDeletes, 0);
  const stale = db(); seed(stale, "users/admin-a", {accountStatus: "active"}); seed(stale, publicPath, {status: "active"}); seed(stale, privatePath, {uploadedBy: "private"}); stale.beforeTransaction = () => seed(stale, publicPath, {status: "deleted"}); let staleDeletes = 0; await assert.rejects(() => applyModerationActionForCaller(stale, admin, request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440065"), {file: () => ({delete: async () => { staleDeletes++; }})}, extension)); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(staleDeletes, 0);
  const replay = db(); seed(replay, "users/admin-a", {accountStatus: "active"}); seed(replay, publicPath, {status: "active"}); seed(replay, privatePath, {uploadedBy: "private"}); let deletes = 0; const bucket = {file: (_path: string) => ({delete: async () => { deletes++; if (deletes === 1) throw new Error("storage-failure"); if (deletes > 2) throw new Error("unexpected-replay"); }})}; const input = request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440066");
  await assert.rejects(() => applyModerationActionForCaller(replay, admin, input, bucket, extension)); const audits = count(replay, "moderation_private_audit/"); const extensionWrites = count(replay, "moderation_private_transaction_extensions/"); assert.equal(replay.data.get(privatePath)?.moderationStatus, "deletionPending"); await applyModerationActionForCaller(replay, admin, input, bucket, extension); assert.equal(replay.data.get(privatePath)?.moderationStatus, "deleted"); await applyModerationActionForCaller(replay, admin, input, bucket, extension); assert.equal(validates, 1); assert.equal(stages, 1); assert.equal(count(replay, "moderation_private_audit/"), audits); assert.equal(count(replay, "moderation_private_transaction_extensions/"), extensionWrites); assert.equal(deletes, 2);
});

test("photo deleted finalize failure and missing object retries do not repeat phase 1 extensions", async () => {
  const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`;
  const finalizeStore = db(); seed(finalizeStore, "users/admin-a", {accountStatus: "active"}); seed(finalizeStore, publicPath, {status: "active"}); seed(finalizeStore, privatePath, {uploadedBy: "private"}); let finalizeValidations = 0; let finalizeStages = 0; let finalizeDeletes = 0; const finalizeExtension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => { finalizeValidations++; }, stage: (_context, port) => { finalizeStages++; port.setPrivateRecord("photo-deleted-finalize-stage", {value: true}); }}; const finalizeBucket = {file: (_path: string) => ({delete: async () => { finalizeDeletes++; if (finalizeDeletes === 1) finalizeStore.transactionFailOnce.add(privatePath); else throw {code: "storage/object-not-found"}; }})}; const finalizeInput = request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440067");
  await assert.rejects(() => applyModerationActionForCaller(finalizeStore, admin, finalizeInput, finalizeBucket, finalizeExtension)); const finalizeAudits = count(finalizeStore, "moderation_private_audit/"); const finalizeWrites = count(finalizeStore, "moderation_private_transaction_extensions/"); assert.equal(finalizeStore.data.get(privatePath)?.moderationStatus, "deletionPending"); await applyModerationActionForCaller(finalizeStore, admin, finalizeInput, finalizeBucket, finalizeExtension); assert.equal(finalizeStore.data.get(privatePath)?.moderationStatus, "deleted"); assert.equal(finalizeValidations, 1); assert.equal(finalizeStages, 1); assert.equal(count(finalizeStore, "moderation_private_audit/"), finalizeAudits); assert.equal(count(finalizeStore, "moderation_private_transaction_extensions/"), finalizeWrites); assert.equal(finalizeDeletes, 2);
  const missingStore = db(); seed(missingStore, "users/admin-a", {accountStatus: "active"}); seed(missingStore, publicPath, {status: "active"}); seed(missingStore, privatePath, {uploadedBy: "private"}); let missingStages = 0; const missingExtension: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: (_context, port) => { missingStages++; port.setPrivateRecord("photo-deleted-missing-stage", {value: true}); }}; const missingBucket = {file: (_path: string) => ({delete: async () => { throw {code: 404}; }})};
  await applyModerationActionForCaller(missingStore, admin, request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440068"), missingBucket, missingExtension); assert.equal(missingStore.data.get(privatePath)?.moderationStatus, "deleted"); assert.equal(missingStages, 1); assert.equal(count(missingStore, "moderation_private_transaction_extensions/"), 1);
});

test("photo deleted finalize extension commits after Storage and treats object-not-found as safe", async () => {
  const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; const store = db(); const calls: string[] = []; const extension: ModerationTransactionExtension = {phase: "finalize", metadata: {kind: "test"}, validate: (context) => { calls.push("validate"); assert.equal(context.phase, "finalize"); assert.equal(context.previousStatus, "deletionPending"); assert.equal(context.nextStatus, "deleted"); }, stage: (context, port) => { calls.push("stage"); port.setPrivateRecord("photo-finalize-stage", {status: context.nextStatus!}); }}; const bucket = {file: (_path: string) => ({delete: async () => { throw {code: "storage/object-not-found"}; }})};
  seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active"}); seed(store, privatePath, {uploadedBy: "private"}); const result = await applyModerationActionForCaller(store, admin, request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440070"), bucket, undefined, extension);
  assert.equal(result.ok, true); assert.deepEqual(calls, ["validate", "stage"]); assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "deleted"); assert.ok(store.data.get(privatePath)?.deletionCompletedAt); assert.deepEqual(store.data.get("moderation_private_transaction_extensions/photo-finalize-stage"), {status: "deleted"}); assert.equal("deletionCompletedAt" in (store.data.get(publicPath) ?? {}), false);
});

test("photo deleted finalize extension failures retain pending state and do not run after Storage failure", async () => {
  const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; const prepare = () => { const store = db(); seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active"}); seed(store, privatePath, {uploadedBy: "private"}); return store; }; const input = request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440071");
  const assertPending = (store: ReturnType<typeof db>) => { assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "deletionPending"); assert.equal(store.data.get(privatePath)?.deletionCompletedAt, undefined); assert.equal(count(store, "moderation_private_transaction_extensions/"), 0); };
  const validateStore = prepare(); let validateStages = 0; const validateFailure: ModerationTransactionExtension = {phase: "finalize", metadata: {kind: "test"}, validate: () => { throw new Error("finalize-validate"); }, stage: () => { validateStages++; }}; await assert.rejects(() => applyModerationActionForCaller(validateStore, admin, input, {file: () => ({delete: async () => undefined})}, undefined, validateFailure)); assert.equal(validateStages, 0); assertPending(validateStore);
  const stageStore = prepare(); const stageFailure: ModerationTransactionExtension = {phase: "finalize", metadata: {kind: "test"}, validate: () => undefined, stage: () => { throw new Error("finalize-stage"); }}; await assert.rejects(() => applyModerationActionForCaller(stageStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440072"}, {file: () => ({delete: async () => undefined})}, undefined, stageFailure)); assertPending(stageStore);
  const portStore = prepare(); portStore.fail.add("moderation_private_transaction_extensions/photo-finalize-stage"); const portFailure: ModerationTransactionExtension = {phase: "finalize", metadata: {kind: "test"}, validate: () => undefined, stage: (_context, port) => port.setPrivateRecord("photo-finalize-stage", {value: true})}; await assert.rejects(() => applyModerationActionForCaller(portStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440073"}, {file: () => ({delete: async () => undefined})}, undefined, portFailure)); assertPending(portStore);
  const storageStore = prepare(); let storageValidations = 0; let storageStages = 0; const storageExtension: ModerationTransactionExtension = {phase: "finalize", metadata: {kind: "test"}, validate: () => { storageValidations++; }, stage: () => { storageStages++; }}; await assert.rejects(() => applyModerationActionForCaller(storageStore, admin, {...input, requestId: "550e8400-e29b-41d4-a716-446655440074"}, {file: () => ({delete: async () => { throw new Error("storage-failure"); }})}, undefined, storageExtension)); assert.equal(storageValidations, 0); assert.equal(storageStages, 0); assertPending(storageStore);
});

test("photo deleted finalize retry reruns only the finalize extension and completed replay is a no-op", async () => {
  const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; const store = db(); let phaseOneStages = 0; let finalizeValidations = 0; let finalizeStages = 0; let deletes = 0; const phaseOne: ModerationTransactionExtension = {phase: "mutation", metadata: {kind: "test"}, validate: () => undefined, stage: (_context, port) => { phaseOneStages++; port.setPrivateRecord("photo-phase-one-stage", {value: true}); }}; const finalize: ModerationTransactionExtension = {phase: "finalize", metadata: {kind: "test"}, validate: () => { finalizeValidations++; }, stage: (_context, port) => { finalizeStages++; if (finalizeStages === 1) throw new Error("finalize-stage"); port.setPrivateRecord("photo-finalize-retry-stage", {value: true}); }}; const bucket = {file: (_path: string) => ({delete: async () => { deletes++; if (deletes > 1) throw {code: 404}; }})};
  seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active"}); seed(store, privatePath, {uploadedBy: "private"}); const input = request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440075");
  await assert.rejects(() => applyModerationActionForCaller(store, admin, input, bucket, phaseOne, finalize)); assert.equal(store.data.get(privatePath)?.moderationStatus, "deletionPending"); const audits = count(store, "moderation_private_audit/"); const dedupes = count(store, "request_deduplication/"); await applyModerationActionForCaller(store, admin, input, bucket, phaseOne, finalize); assert.equal(store.data.get(privatePath)?.moderationStatus, "deleted"); await applyModerationActionForCaller(store, admin, input, bucket, phaseOne, finalize); assert.equal(phaseOneStages, 1); assert.equal(finalizeValidations, 2); assert.equal(finalizeStages, 2); assert.equal(deletes, 2); assert.equal(count(store, "moderation_private_audit/"), audits); assert.equal(count(store, "request_deduplication/"), dedupes); assert.equal(count(store, "moderation_private_transaction_extensions/"), 2);
});

test("photo deleted finalize rejects unexpected private status before invoking its extension", async () => {
  const store = db(); const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; let validates = 0; let stages = 0; const extension: ModerationTransactionExtension = {phase: "finalize", metadata: {kind: "test"}, validate: () => { validates++; }, stage: () => { stages++; }}; const bucket = {file: (_path: string) => ({delete: async () => { seed(store, privatePath, {uploadedBy: "private", moderationStatus: "hidden"}); }})};
  seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active"}); seed(store, privatePath, {uploadedBy: "private"}); await assert.rejects(() => applyModerationActionForCaller(store, admin, request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440076"), bucket, undefined, extension));
  assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "hidden"); assert.equal(validates, 0); assert.equal(stages, 0); assert.equal(count(store, "moderation_private_transaction_extensions/"), 0);
});

test("photo hidden and deleted retain private attribution, use only the formal path, and finalize safely", async () => {
  const store = db(); const deleted: string[] = []; const bucket = {file: (path: string) => ({delete: async () => { deleted.push(path); }})}; seed(store, "users/admin-a", {accountStatus: "active"});
  const publicPath = `vending_machines/${machineId}/photos/p_0123456789abcdef0123456789abcd`; const privatePath = `vending_machine_private/${machineId}/photos/p_0123456789abcdef0123456789abcd`; seed(store, publicPath, {status: "active", createdAt: 1}); seed(store, privatePath, {uploadedBy: "private-actor"});
  const hidden = await applyModerationActionForCaller(store, admin, request({targetType: "photo", machineId, photoId: "p_0123456789abcdef0123456789abcd"}, "hidden", "550e8400-e29b-41d4-a716-446655440010"), bucket); assert.equal(hidden.nextStatus, "hidden"); assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "hidden"); assert.equal(store.data.get(privatePath)?.uploadedBy, "private-actor"); assert.equal(deleted.length, 0);
  const result = await applyModerationActionForCaller(store, admin, request({targetType: "photo", machineId, photoId: "p_0123456789abcdef0123456789abcd"}, "deleted", "550e8400-e29b-41d4-a716-446655440011"), bucket); assert.equal(result.nextStatus, "deleted"); assert.deepEqual(deleted, [`vending_machines/${machineId}/p_0123456789abcdef0123456789abcd/original.jpg`]); assert.equal(store.data.get(privatePath)?.moderationStatus, "deleted"); assert.equal("uploadedBy" in (store.data.get(publicPath) ?? {}), false);
});

test("photo storage failure remains private pending and the same request retries without duplicate audit", async () => {
  const store = db(); let attempts = 0; const bucket = {file: (_path: string) => ({delete: async () => { attempts++; if (attempts === 1) throw new Error("storage failure"); }})}; seed(store, "users/admin-a", {accountStatus: "active"}); const publicPath = `vending_machines/${machineId}/photos/p_0123456789abcdef0123456789abcd`; const privatePath = `vending_machine_private/${machineId}/photos/p_0123456789abcdef0123456789abcd`; seed(store, publicPath, {status: "active"}); seed(store, privatePath, {uploadedBy: "private"}); const input = request({targetType: "photo", machineId, photoId: "p_0123456789abcdef0123456789abcd"}, "deleted", "550e8400-e29b-41d4-a716-446655440012");
  await assert.rejects(() => applyModerationActionForCaller(store, admin, input, bucket)); assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "deletionPending"); const audits = count(store, "moderation_private_audit/"); await applyModerationActionForCaller(store, admin, input, bucket); assert.equal(store.data.get(privatePath)?.moderationStatus, "deleted"); assert.equal(count(store, "moderation_private_audit/"), audits); assert.equal(attempts, 2);
});

test("photo object-not-found finalizes successfully without adding public metadata", async () => {
  const store = db(); const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; const bucket = {file: (_path: string) => ({delete: async () => { throw {code: 404}; }})}; seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active", createdAt: 1}); seed(store, privatePath, {uploadedBy: "private"});
  const result = await applyModerationActionForCaller(store, admin, request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440013"), bucket); assert.equal(result.ok, true); assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "deleted"); assert.ok(store.data.get(privatePath)?.deletionCompletedAt); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); for (const key of ["uploadedBy", "moderatorUid", "actorUid", "storagePath", "deletionPending", "deletionCompletedAt"]) assert.equal(key in (store.data.get(publicPath) ?? {}), false);
});

test("photo finalize failure stays pending and same-request retry finalizes without duplicate audit", async () => {
  const store = db(); const photo = "p_0123456789abcdef0123456789abcd"; const publicPath = `vending_machines/${machineId}/photos/${photo}`; const privatePath = `vending_machine_private/${machineId}/photos/${photo}`; let deletes = 0; const bucket = {file: (_path: string) => ({delete: async () => { deletes++; if (deletes === 1) store.transactionFailOnce.add(privatePath); else throw {code: "storage/object-not-found"}; }})}; seed(store, "users/admin-a", {accountStatus: "active"}); seed(store, publicPath, {status: "active"}); seed(store, privatePath, {uploadedBy: "private"}); const input = request({targetType: "photo", machineId, photoId: photo}, "deleted", "550e8400-e29b-41d4-a716-446655440014");
  await assert.rejects(() => applyModerationActionForCaller(store, admin, input, bucket)); assert.equal(store.data.get(publicPath)?.status, "inactive"); assert.equal(store.data.get(privatePath)?.moderationStatus, "deletionPending"); const audits = count(store, "moderation_private_audit/"); await applyModerationActionForCaller(store, admin, input, bucket); assert.equal(store.data.get(privatePath)?.moderationStatus, "deleted"); assert.ok(store.data.get(privatePath)?.deletionCompletedAt); assert.equal(count(store, "moderation_private_audit/"), audits); const replay = await applyModerationActionForCaller(store, admin, input, bucket); assert.equal(replay.ok, true); assert.equal(count(store, "moderation_private_audit/"), audits); assert.equal(deletes, 2);
});
