import assert from "node:assert/strict";
import test from "node:test";
import {createFirestoreModerationReadStore, listModerationQueueForCaller} from "../src/moderation_read";
import {applyModerationQueueActionForCaller, markModerationItemInReviewForCaller, resolveModerationItemForCaller} from "../src/moderation_queue_mutation";

type Data = Record<string, unknown>;
class FakeDb { data = new Map<string, Data>(); fail = new Set<string>(); beforeTransaction: (() => void) | undefined; collection(id: string) { return new Col(this, id); } async runTransaction<T>(work: (transaction: Tx) => Promise<T>) { this.beforeTransaction?.(); this.beforeTransaction = undefined; const transaction = new Tx(this); const result = await work(transaction); transaction.commit(); return result; } }
class Col { constructor(readonly db: FakeDb, readonly path: string) {} doc(id: string) { return new Doc(this.db, `${this.path}/${id}`); } where(field: string, _operator: string, values: unknown) { return new Query(this.db, this.path, field, values); } }
class Doc { constructor(readonly db: FakeDb, readonly path: string) {} collection(id: string) { return new Col(this.db, `${this.path}/${id}`); } async get() { return snap(this.db.data.get(this.path)); } }
class Query { constructor(readonly db: FakeDb, readonly path: string, readonly field: string, readonly values: unknown) {} orderBy(_field: string, _direction: string) { return this; } limit(_limit: number) { return this; } async get() { const allowed = Array.isArray(this.values) ? this.values : [this.values]; return {docs: [...this.db.data.entries()].filter(([path, value]) => path.startsWith(`${this.path}/`) && !path.slice(this.path.length + 1).includes("/") && allowed.includes(value[this.field])).map(([path, value]) => ({id: path.split("/").at(-1)!, data: () => value, exists: true}))}; } }
class Tx { staged = new Map<string, Data>(); constructor(readonly db: FakeDb) {} async get(document: Doc | Query): Promise<any> { if (document instanceof Query) { const allowed = Array.isArray(document.values) ? document.values : [document.values]; return {docs: [...this.db.data.entries()].filter(([path, value]) => path.startsWith(`${document.path}/`) && !path.slice(document.path.length + 1).includes("/") && allowed.includes(value[document.field])).map(([path, value]) => ({ref: new Doc(this.db, path), ...snap(value)}))}; } return snap(this.staged.get(document.path) ?? this.db.data.get(document.path)); } update(document: Doc, value: Data) { if (!this.db.data.has(document.path)) throw new Error("missing"); this.stage(document.path, {...(this.db.data.get(document.path) ?? {}), ...value}); } set(document: Doc, value: Data, options?: {merge?: boolean}) { this.stage(document.path, options?.merge ? {...(this.db.data.get(document.path) ?? {}), ...value} : value); } create(document: Doc, value: Data) { if (this.db.data.has(document.path)) throw new Error("exists"); this.stage(document.path, value); } stage(path: string, value: Data) { if (this.db.fail.has(path) || [...this.db.fail].some((prefix) => prefix.endsWith("/") && path.startsWith(prefix))) throw new Error(`injected:${path}`); this.staged.set(path, value); } commit() { for (const [path, value] of this.staged) this.db.data.set(path, value); } }
class FakeBucket { deleted: string[] = []; failure: unknown | undefined; onDelete: (() => void) | undefined; file(path: string) { return {delete: async () => { this.deleted.push(path); this.onDelete?.(); if (this.failure !== undefined) throw this.failure; }}; } }
function snap(value: Data | undefined) { return {exists: value !== undefined, data: () => value}; }
const db = () => new FakeDb() as unknown as import("firebase-admin/firestore").Firestore & {data: Map<string, Data>; fail: Set<string>; beforeTransaction: (() => void) | undefined};
const caller = {uid: "admin", customClaims: {admin: true}};
const request = (sourceType: "report" | "correction", itemId: string, requestId: string) => ({queueRef: {sourceType, itemId}, requestId});
const resolveRequest = (sourceType: "report" | "correction", itemId: string, resolution: "noAction" | "rejected", reason: string, requestId: string) => ({queueRef: {sourceType, itemId}, resolution, reason, requestId});
const actionRequest = (sourceType: "report" | "correction", itemId: string, action: string, requestId: string, target?: Data) => ({queueRef: {sourceType, itemId}, action, reason: "moderation reason", requestId, ...(target === undefined ? {} : {target})});
const seedAdmin = (store: ReturnType<typeof db>) => store.data.set("users/admin", {accountStatus: "active"});
const count = (store: ReturnType<typeof db>, prefix: string) => [...store.data.keys()].filter((path) => path.startsWith(prefix)).length;

test("queue inReview requires an active administrator", async () => {
  const store = db(); store.data.set("users/admin", {accountStatus: "active"}); store.data.set("machine_reports/report-1", {status: "new", targetType: "machine", machineId: "machine-1"}); await assert.rejects(() => markModerationItemInReviewForCaller(store, {uid: "admin", customClaims: {}}, request("report", "report-1", "550e8400-e29b-41d4-a716-446655440079"))); store.data.set("users/admin", {accountStatus: "restricted"}); await assert.rejects(() => markModerationItemInReviewForCaller(store, caller, request("report", "report-1", "550e8400-e29b-41d4-a716-44665544007a"))); assert.equal(store.data.get("machine_reports/report-1")?.status, "new");
});

test("report and correction transition new items to inReview with private audit and safe results", async () => {
  for (const [sourceType, path, itemId, data, requestId] of [["report", "machine_reports", "report-1", {status: "new", targetType: "machine", machineId: "machine-1", createdAt: 1}, "550e8400-e29b-41d4-a716-446655440080"], ["correction", "machine_corrections", "correction-1", {status: "new", machineId: "machine-2", createdAt: 2}, "550e8400-e29b-41d4-a716-446655440081"]] as const) { const store = db(); seedAdmin(store); store.data.set(`${path}/${itemId}`, data); const result = await markModerationItemInReviewForCaller(store, caller, request(sourceType, itemId, requestId)); assert.equal(result.status, "inReview"); assert.equal(result.changed, true); assert.equal(store.data.get(`${path}/${itemId}`)?.status, "inReview"); assert.equal(count(store, "moderation_private_queue_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); assert.equal(JSON.stringify(result).includes("admin"), false); }
});

test("inReview is a safe no-op while terminal or malformed queue items fail closed", async () => {
  const store = db(); seedAdmin(store); store.data.set("machine_reports/in-review", {status: "inReview", targetType: "machine", machineId: "machine-1"}); const noOp = await markModerationItemInReviewForCaller(store, caller, request("report", "in-review", "550e8400-e29b-41d4-a716-446655440082")); assert.equal(noOp.changed, false); assert.equal(count(store, "moderation_private_queue_audit/"), 0);
  const invalidCases: ReadonlyArray<readonly [string, Data]> = [["resolved", {status: "resolved", targetType: "machine", machineId: "machine-1"}], ["pending", {status: "resolutionPending", targetType: "machine", machineId: "machine-1"}], ["malformed", {status: "new", targetType: "photo", machineId: "machine-1"}]];
  for (const [id, data] of invalidCases) { store.data.set(`machine_reports/${id}`, data); await assert.rejects(() => markModerationItemInReviewForCaller(store, caller, request("report", id, id === "resolved" ? "550e8400-e29b-41d4-a716-446655440083" : id === "pending" ? "550e8400-e29b-41d4-a716-446655440084" : "550e8400-e29b-41d4-a716-446655440085"))); }
  assert.equal(count(store, "moderation_private_queue_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0);
});

test("queue inReview dedupe and transaction reread prevent duplicate audits", async () => {
  const store = db(); seedAdmin(store); store.data.set("machine_reports/report-1", {status: "new", targetType: "machine", machineId: "machine-1", createdAt: 1}); const input = request("report", "report-1", "550e8400-e29b-41d4-a716-446655440086"); await markModerationItemInReviewForCaller(store, caller, input); const audits = count(store, "moderation_private_queue_audit/"); await markModerationItemInReviewForCaller(store, caller, input); assert.equal(count(store, "moderation_private_queue_audit/"), audits); assert.equal(count(store, "request_deduplication/"), 1);
  const race = db(); seedAdmin(race); race.data.set("machine_reports/report-2", {status: "new", targetType: "machine", machineId: "machine-2"}); race.beforeTransaction = () => race.data.set("machine_reports/report-2", {status: "inReview", targetType: "machine", machineId: "machine-2"}); const result = await markModerationItemInReviewForCaller(race, caller, request("report", "report-2", "550e8400-e29b-41d4-a716-446655440087")); assert.equal(result.changed, false); assert.equal(count(race, "moderation_private_queue_audit/"), 0);
});

test("inReview and resolutionPending remain in the moderation queue and private audit data is not returned", async () => {
  const store = db(); seedAdmin(store); store.data.set("machine_reports/report-1", {status: "new", targetType: "machine", machineId: "machine-1", category: "other", createdAt: 1, submittedBy: "private"}); store.data.set("machine_reports/pending", {status: "resolutionPending", targetType: "machine", machineId: "machine-2", category: "other", createdAt: 2, submittedBy: "private"}); await markModerationItemInReviewForCaller(store, caller, request("report", "report-1", "550e8400-e29b-41d4-a716-446655440088")); const page = await listModerationQueueForCaller(createFirestoreModerationReadStore(store), caller, {limit: 10}); assert.deepEqual(page.items.map((item) => item.id), ["report-1", "pending"]); assert.equal(JSON.stringify(page).includes("private"), false);
});

test("report queue items resolve from new or inReview without mutating their target", async () => {
  for (const [id, status, resolution, requestId] of [["new", "new", "noAction", "550e8400-e29b-41d4-a716-446655440089"], ["review", "inReview", "noAction", "550e8400-e29b-41d4-a716-44665544008a"], ["rejected", "new", "rejected", "550e8400-e29b-41d4-a716-44665544008b"]] as const) {
    const store = db(); seedAdmin(store); store.data.set(`machine_reports/${id}`, {status, targetType: "machine", machineId: "machine-1", submittedBy: "private"}); store.data.set("vending_machines/machine-1", {status: "active"}); store.data.set("machine_product_index/machine-1_product-1", {isActive: true});
    const result = await resolveModerationItemForCaller(store, caller, resolveRequest("report", id, resolution, "  reviewed safely  ", requestId));
    assert.equal(result.status, "resolved"); assert.equal(result.resolution, resolution); assert.equal(store.data.get(`machine_reports/${id}`)?.status, "resolved"); assert.equal(store.data.get(`machine_reports/${id}`)?.resolution, resolution); assert.equal(store.data.get("vending_machines/machine-1")?.status, "active"); assert.equal(store.data.get("machine_product_index/machine-1_product-1")?.isActive, true); assert.equal(count(store, "moderation_private_queue_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); assert.equal(JSON.stringify(result).includes("private"), false);
  }
});

test("correction queue items resolve as noAction or rejected without applying the correction", async () => {
  for (const [id, resolution, requestId] of [["no-action", "noAction", "550e8400-e29b-41d4-a716-44665544008c"], ["rejected", "rejected", "550e8400-e29b-41d4-a716-44665544008d"]] as const) {
    const store = db(); seedAdmin(store); store.data.set(`machine_corrections/${id}`, {status: "new", machineId: "machine-2", proposedName: "must not apply"}); store.data.set("vending_machines/machine-2", {status: "active", name: "unchanged"});
    await resolveModerationItemForCaller(store, caller, resolveRequest("correction", id, resolution, "reviewed", requestId));
    assert.equal(store.data.get(`machine_corrections/${id}`)?.status, "resolved"); assert.equal(store.data.get("vending_machines/machine-2")?.name, "unchanged"); assert.equal(count(store, "moderation_private_queue_audit/"), 1);
  }
});

test("queue resolution rejects terminal, pending, malformed, invalid resolution, and invalid reasons", async () => {
  const store = db(); seedAdmin(store);
  const invalidItems: ReadonlyArray<readonly [string, Data]> = [["resolved", {status: "resolved", targetType: "machine", machineId: "machine-1"}], ["pending", {status: "resolutionPending", targetType: "machine", machineId: "machine-1"}], ["malformed", {status: "new", targetType: "photo", machineId: "machine-1"}]];
  for (const [id, data] of invalidItems) { store.data.set(`machine_reports/${id}`, data); await assert.rejects(() => resolveModerationItemForCaller(store, caller, resolveRequest("report", id, "noAction", "reviewed", id === "resolved" ? "550e8400-e29b-41d4-a716-44665544008e" : id === "pending" ? "550e8400-e29b-41d4-a716-44665544008f" : "550e8400-e29b-41d4-a716-446655440090"))); }
  store.data.set("machine_reports/valid", {status: "new", targetType: "machine", machineId: "machine-1"});
  await assert.rejects(() => resolveModerationItemForCaller(store, caller, {...resolveRequest("report", "valid", "noAction", " ", "550e8400-e29b-41d4-a716-446655440091")}));
  await assert.rejects(() => resolveModerationItemForCaller(store, caller, {...resolveRequest("report", "valid", "noAction", "valid", "550e8400-e29b-41d4-a716-446655440092"), resolution: "actionTaken"}));
  assert.equal(count(store, "moderation_private_queue_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0);
});

test("queue resolution dedupe and transaction reread prevent duplicate audit and queue updates", async () => {
  const store = db(); seedAdmin(store); store.data.set("machine_reports/report-1", {status: "new", targetType: "machine", machineId: "machine-1"}); const input = resolveRequest("report", "report-1", "noAction", "reviewed", "550e8400-e29b-41d4-a716-446655440093"); const first = await resolveModerationItemForCaller(store, caller, input); const replay = await resolveModerationItemForCaller(store, caller, input); assert.deepEqual(replay, first); assert.equal(count(store, "moderation_private_queue_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1);
  const race = db(); seedAdmin(race); race.data.set("machine_reports/report-2", {status: "new", targetType: "machine", machineId: "machine-2"}); race.beforeTransaction = () => race.data.set("machine_reports/report-2", {status: "resolved", resolution: "noAction", targetType: "machine", machineId: "machine-2"}); await assert.rejects(() => resolveModerationItemForCaller(race, caller, resolveRequest("report", "report-2", "rejected", "reviewed", "550e8400-e29b-41d4-a716-446655440094"))); assert.equal(count(race, "moderation_private_queue_audit/"), 0); assert.equal(count(race, "request_deduplication/"), 0);
});

test("resolved queue items are excluded while new, inReview, and pending remain visible", async () => {
  const store = db(); seedAdmin(store); store.data.set("machine_reports/new", {status: "new", targetType: "machine", machineId: "machine-1", category: "other", createdAt: 1}); store.data.set("machine_reports/review", {status: "inReview", targetType: "machine", machineId: "machine-2", category: "other", createdAt: 2}); store.data.set("machine_reports/pending", {status: "resolutionPending", targetType: "machine", machineId: "machine-3", category: "other", createdAt: 3}); store.data.set("machine_reports/resolve", {status: "new", targetType: "machine", machineId: "machine-4", category: "other", createdAt: 4}); await resolveModerationItemForCaller(store, caller, resolveRequest("report", "resolve", "rejected", "reviewed", "550e8400-e29b-41d4-a716-446655440095")); const page = await listModerationQueueForCaller(createFirestoreModerationReadStore(store), caller, {limit: 10}); assert.deepEqual(page.items.map((item) => item.id), ["new", "review", "pending"]);
});

test("queue-linked machine actionTaken mutates report and correction targets atomically", async () => {
  for (const [sourceType, collection, itemId, machineId, action, requestId] of [["report", "machine_reports", "report-machine", "machine-report", "underReview", "550e8400-e29b-41d4-a716-446655440096"], ["correction", "machine_corrections", "correction-machine", "machine-correction", "underReview", "550e8400-e29b-41d4-a716-446655440097"]] as const) {
    const store = db(); seedAdmin(store); store.data.set(`${collection}/${itemId}`, sourceType === "report" ? {status: "new", targetType: "machine", machineId} : {status: "inReview", machineId}); store.data.set(`vending_machines/${machineId}`, {status: "active"}); store.data.set(`machine_product_index/${machineId}_a`, {machineId, isActive: true});
    const result = await applyModerationQueueActionForCaller(store, caller, actionRequest(sourceType, itemId, action, requestId));
    assert.equal(result.status, "resolved"); assert.equal(result.resolution, "actionTaken"); assert.equal(result.machineId, machineId); assert.equal(result.previousStatus, "active"); assert.equal(result.nextStatus, "underReview"); assert.equal(store.data.get(`vending_machines/${machineId}`)?.status, "underReview"); assert.equal(store.data.get(`machine_product_index/${machineId}_a`)?.machineStatus, "underReview"); assert.equal(store.data.get(`${collection}/${itemId}`)?.status, "resolved"); assert.equal(store.data.get(`${collection}/${itemId}`)?.resolution, "actionTaken"); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); assert.equal(JSON.stringify(result).includes("admin"), false);
  }
});

test("queue-linked machine actionTaken follows machine transitions and excludes resolved items", async () => {
  const store = db(); seedAdmin(store); store.data.set("machine_reports/first", {status: "new", targetType: "machine", machineId: "machine-1", category: "other", createdAt: 1}); store.data.set("vending_machines/machine-1", {status: "active"}); await applyModerationQueueActionForCaller(store, caller, actionRequest("report", "first", "underReview", "550e8400-e29b-41d4-a716-446655440098")); store.data.set("machine_reports/second", {status: "inReview", targetType: "machine", machineId: "machine-1", category: "other", createdAt: 2}); await applyModerationQueueActionForCaller(store, caller, actionRequest("report", "second", "hidden", "550e8400-e29b-41d4-a716-446655440099")); assert.equal(store.data.get("vending_machines/machine-1")?.status, "hidden"); const page = await listModerationQueueForCaller(createFirestoreModerationReadStore(store), caller, {limit: 10}); assert.deepEqual(page.items, []);
});

test("queue-linked machine actionTaken preserves the existing hidden, removed, and merged transitions", async () => {
  for (const [action, requestId] of [["hidden", "550e8400-e29b-41d4-a716-4466554400a0"], ["removed", "550e8400-e29b-41d4-a716-4466554400a1"], ["merged", "550e8400-e29b-41d4-a716-4466554400a2"]] as const) { const store = db(); seedAdmin(store); store.data.set("machine_reports/item", {status: "inReview", targetType: "machine", machineId: "machine-1"}); store.data.set("vending_machines/machine-1", {status: "underReview"}); const result = await applyModerationQueueActionForCaller(store, caller, actionRequest("report", "item", action, requestId)); assert.equal(result.nextStatus, action); assert.equal(store.data.get("vending_machines/machine-1")?.status, action); assert.equal(store.data.get("machine_reports/item")?.resolution, "actionTaken"); }
});

test("queue-linked machine actionTaken rejects malformed, mismatched, pending, and resolved queue items", async () => {
  const store = db(); seedAdmin(store); store.data.set("vending_machines/machine-1", {status: "active"});
  const invalid: ReadonlyArray<readonly [string, Data]> = [["photo", {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}], ["pending", {status: "resolutionPending", targetType: "machine", machineId: "machine-1"}], ["resolved", {status: "resolved", targetType: "machine", machineId: "machine-1"}], ["malformed", {status: "new", targetType: "machine"}]];
  for (const [itemId, data] of invalid) { store.data.set(`machine_reports/${itemId}`, data); await assert.rejects(() => applyModerationQueueActionForCaller(store, caller, actionRequest("report", itemId, "underReview", itemId === "photo" ? "550e8400-e29b-41d4-a716-44665544009a" : itemId === "pending" ? "550e8400-e29b-41d4-a716-44665544009b" : itemId === "resolved" ? "550e8400-e29b-41d4-a716-44665544009c" : "550e8400-e29b-41d4-a716-44665544009d"))); }
  store.data.set("machine_reports/mismatch", {status: "new", targetType: "machine", machineId: "machine-1"}); await assert.rejects(() => applyModerationQueueActionForCaller(store, caller, actionRequest("report", "mismatch", "underReview", "550e8400-e29b-41d4-a716-44665544009e", {targetType: "machine", machineId: "other"}))); assert.equal(store.data.get("vending_machines/machine-1")?.status, "active"); assert.equal(count(store, "moderation_private_audit/"), 0);
});

test("queue-linked machine actionTaken dedupe, races, and all staged-write failures roll back", async () => {
  const prepare = () => { const store = db(); seedAdmin(store); store.data.set("machine_reports/item", {status: "new", targetType: "machine", machineId: "machine-1"}); store.data.set("vending_machines/machine-1", {status: "active"}); store.data.set("machine_product_index/machine-1_a", {machineId: "machine-1", isActive: true}); return store; };
  const input = actionRequest("report", "item", "underReview", "550e8400-e29b-41d4-a716-44665544009f"); const replay = prepare(); const first = await applyModerationQueueActionForCaller(replay, caller, input); const second = await applyModerationQueueActionForCaller(replay, caller, input); assert.deepEqual(second, first); assert.equal(count(replay, "moderation_private_audit/"), 1); assert.equal(count(replay, "request_deduplication/"), 1);
  const race = prepare(); race.beforeTransaction = () => race.data.set("machine_reports/item", {status: "resolved", resolution: "actionTaken", targetType: "machine", machineId: "machine-1"}); await assert.rejects(() => applyModerationQueueActionForCaller(race, caller, input)); assert.equal(race.data.get("vending_machines/machine-1")?.status, "active"); assert.equal(count(race, "moderation_private_audit/"), 0);
  for (const failedPath of ["vending_machines/machine-1", "machine_product_index/machine-1_a", "machine_reports/item", "moderation_private_audit/" , "request_deduplication/"]) { const failure = prepare(); if (failedPath.endsWith("/")) { const original = failure.fail.add.bind(failure.fail); original(failedPath); } else failure.fail.add(failedPath); await assert.rejects(() => applyModerationQueueActionForCaller(failure, caller, {...input, requestId: input.requestId.slice(0, -1) + "0"})); assert.equal(failure.data.get("vending_machines/machine-1")?.status, "active"); assert.equal(failure.data.get("machine_product_index/machine-1_a")?.isActive, true); assert.equal(failure.data.get("machine_reports/item")?.status, "new"); assert.equal(count(failure, "moderation_private_audit/"), 0); assert.equal(count(failure, "request_deduplication/"), 0); }
});

test("queue-linked product actionTaken deactivates only the machine relation and index for report and correction", async () => {
  for (const [sourceType, collection, itemId, requestId] of [["report", "machine_reports", "product-report", "550e8400-e29b-41d4-a716-4466554400a3"], ["correction", "machine_corrections", "product-correction", "550e8400-e29b-41d4-a716-4466554400a4"]] as const) { const store = db(); seedAdmin(store); const queue = sourceType === "report" ? {status: "new", targetType: "product", machineId: "machine-1", productId: "product-1", category: "other", createdAt: 1} : {status: "inReview", targetType: "product", machineId: "machine-1", productId: "product-1", createdAt: 1}; store.data.set(`${collection}/${itemId}`, queue); store.data.set("vending_machines/machine-1/products/product-1", {isActive: true}); store.data.set("machine_product_index/machine-1_product-1", {isActive: true}); store.data.set("vending_machines/machine-1/products/other", {isActive: true}); store.data.set("machine_product_index/machine-1_other", {isActive: true}); store.data.set("products/product-1", {name: "master stays unchanged"}); const result = await applyModerationQueueActionForCaller(store, caller, actionRequest(sourceType, itemId, "inactive", requestId)); assert.equal(result.targetType, "product"); assert.equal(result.productId, "product-1"); assert.equal(store.data.get("vending_machines/machine-1/products/product-1")?.isActive, false); assert.equal(store.data.get("machine_product_index/machine-1_product-1")?.isActive, false); assert.equal(store.data.get("vending_machines/machine-1/products/other")?.isActive, true); assert.equal(store.data.get("machine_product_index/machine-1_other")?.isActive, true); assert.deepEqual(store.data.get("products/product-1"), {name: "master stays unchanged"}); assert.equal(store.data.get(`${collection}/${itemId}`)?.resolution, "actionTaken"); assert.equal(count(store, "moderation_private_audit/"), 1); }
});

test("queue-linked product actionTaken rejects inconsistent targets and state without resolving queue", async () => {
  const invalid = (queue: Data, relation: Data | undefined, index: Data | undefined, id: string) => ({queue, relation, index, id}); const cases = [invalid({status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}, {isActive: true}, {isActive: true}, "wrong-type"), invalid({status: "new", targetType: "product", machineId: "machine-1"}, {isActive: true}, {isActive: true}, "missing-product"), invalid({status: "resolutionPending", targetType: "product", machineId: "machine-1", productId: "product-1"}, {isActive: true}, {isActive: true}, "pending"), invalid({status: "resolved", targetType: "product", machineId: "machine-1", productId: "product-1"}, {isActive: true}, {isActive: true}, "resolved"), invalid({status: "new", targetType: "product", machineId: "machine-1", productId: "product-1"}, undefined, {isActive: true}, "relation-missing"), invalid({status: "new", targetType: "product", machineId: "machine-1", productId: "product-1"}, {isActive: false}, {isActive: true}, "relation-inactive"), invalid({status: "new", targetType: "product", machineId: "machine-1", productId: "product-1"}, {isActive: true}, undefined, "index-missing"), invalid({status: "new", targetType: "product", machineId: "machine-1", productId: "product-1"}, {isActive: true}, {isActive: false}, "index-inconsistent")]; for (const entry of cases) { const store = db(); seedAdmin(store); store.data.set(`machine_reports/${entry.id}`, entry.queue); if (entry.relation) store.data.set("vending_machines/machine-1/products/product-1", entry.relation); if (entry.index) store.data.set("machine_product_index/machine-1_product-1", entry.index); await assert.rejects(() => applyModerationQueueActionForCaller(store, caller, actionRequest("report", entry.id, "inactive", `550e8400-e29b-41d4-a716-446655440${entry.id === "wrong-type" ? "0a5" : entry.id === "missing-product" ? "0a6" : entry.id === "pending" ? "0a7" : entry.id === "resolved" ? "0a8" : entry.id === "relation-missing" ? "0a9" : entry.id === "relation-inactive" ? "0aa" : entry.id === "index-missing" ? "0ab" : "0ac"}`))); assert.equal(store.data.get(`machine_reports/${entry.id}`)?.status, entry.queue.status, entry.id); assert.equal(count(store, "moderation_private_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0); }
});

test("queue-linked product actionTaken dedupe, races, and write failures are atomic", async () => {
  const prepare = () => { const store = db(); seedAdmin(store); store.data.set("machine_reports/item", {status: "new", targetType: "product", machineId: "machine-1", productId: "product-1"}); store.data.set("vending_machines/machine-1/products/product-1", {isActive: true}); store.data.set("machine_product_index/machine-1_product-1", {isActive: true}); store.data.set("products/product-1", {name: "master"}); return store; }; const input = actionRequest("report", "item", "inactive", "550e8400-e29b-41d4-a716-4466554400ad"); const replay = prepare(); await applyModerationQueueActionForCaller(replay, caller, input); await applyModerationQueueActionForCaller(replay, caller, input); assert.equal(count(replay, "moderation_private_audit/"), 1); assert.equal(count(replay, "request_deduplication/"), 1); const race = prepare(); race.beforeTransaction = () => race.data.set("machine_reports/item", {status: "resolved", resolution: "actionTaken", targetType: "product", machineId: "machine-1", productId: "product-1"}); await assert.rejects(() => applyModerationQueueActionForCaller(race, caller, input)); assert.equal(race.data.get("vending_machines/machine-1/products/product-1")?.isActive, true); for (const failedPath of ["vending_machines/machine-1/products/product-1", "machine_product_index/machine-1_product-1", "machine_reports/item", "moderation_private_audit/", "request_deduplication/"]) { const failure = prepare(); failure.fail.add(failedPath); await assert.rejects(() => applyModerationQueueActionForCaller(failure, caller, {...input, requestId: input.requestId.slice(0, -1) + "0"})); assert.equal(failure.data.get("vending_machines/machine-1/products/product-1")?.isActive, true); assert.equal(failure.data.get("machine_product_index/machine-1_product-1")?.isActive, true); assert.equal(failure.data.get("machine_reports/item")?.status, "new"); assert.deepEqual(failure.data.get("products/product-1"), {name: "master"}); assert.equal(count(failure, "moderation_private_audit/"), 0); assert.equal(count(failure, "request_deduplication/"), 0); }
});

test("queue-linked user actionTaken updates only accountStatus for report and correction", async () => {
  for (const [sourceType, collection, itemId, action, initialStatus, expectedStatus, requestId] of [["report", "machine_reports", "user-report", "restricted", "active", "restricted", "550e8400-e29b-41d4-a716-4466554400ae"], ["correction", "machine_corrections", "user-correction", "suspended", "active", "suspended", "550e8400-e29b-41d4-a716-4466554400af"], ["report", "machine_reports", "user-reactivate-restricted", "active", "restricted", "active", "550e8400-e29b-41d4-a716-4466554400b0"], ["correction", "machine_corrections", "user-reactivate-suspended", "active", "suspended", "active", "550e8400-e29b-41d4-a716-4466554400b1"]] as const) { const store = db(); seedAdmin(store); store.data.set(`${collection}/${itemId}`, {status: "new", targetType: "user", targetUserId: "target-user", category: "other", createdAt: 1}); store.data.set("users/target-user", {accountStatus: initialStatus, email: "private@example.invalid", displayName: "private"}); const result = await applyModerationQueueActionForCaller(store, caller, actionRequest(sourceType, itemId, action, requestId)); assert.equal(result.targetType, "user"); assert.equal(result.targetUserId, "target-user"); assert.equal(store.data.get("users/target-user")?.accountStatus, expectedStatus); assert.equal(store.data.get("users/target-user")?.email, "private@example.invalid"); assert.equal(store.data.get(`${collection}/${itemId}`)?.resolution, "actionTaken"); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(JSON.stringify(result).includes("private"), false); }
});

test("queue-linked user actionTaken rejects invalid target, lifecycle, transition, and mismatched user", async () => {
  const cases: ReadonlyArray<readonly [string, Data, string, Data | undefined, string]> = [["wrong-type", {status: "new", targetType: "machine", machineId: "machine-1"}, "restricted", undefined, "550e8400-e29b-41d4-a716-4466554400b2"], ["missing-user", {status: "new", targetType: "user"}, "restricted", undefined, "550e8400-e29b-41d4-a716-4466554400b3"], ["pending", {status: "resolutionPending", targetType: "user", targetUserId: "target-user"}, "restricted", undefined, "550e8400-e29b-41d4-a716-4466554400b4"], ["resolved", {status: "resolved", targetType: "user", targetUserId: "target-user"}, "restricted", undefined, "550e8400-e29b-41d4-a716-4466554400b5"], ["invalid-transition", {status: "new", targetType: "user", targetUserId: "target-user"}, "restricted", {accountStatus: "restricted"}, "550e8400-e29b-41d4-a716-4466554400b6"]];
  for (const [itemId, queue, action, target, requestId] of cases) { const store = db(); seedAdmin(store); store.data.set(`machine_reports/${itemId}`, queue); if (target) store.data.set("users/target-user", target); await assert.rejects(() => applyModerationQueueActionForCaller(store, caller, actionRequest("report", itemId, action, requestId))); assert.equal(store.data.get(`machine_reports/${itemId}`)?.status, queue.status); assert.equal(count(store, "moderation_private_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0); }
  const mismatch = db(); seedAdmin(mismatch); mismatch.data.set("machine_reports/mismatch", {status: "new", targetType: "user", targetUserId: "target-user"}); mismatch.data.set("users/target-user", {accountStatus: "active"}); await assert.rejects(() => applyModerationQueueActionForCaller(mismatch, caller, actionRequest("report", "mismatch", "restricted", "550e8400-e29b-41d4-a716-4466554400b7", {targetType: "user", targetUserId: "other-user"}))); assert.equal(mismatch.data.get("users/target-user")?.accountStatus, "active");
});

test("queue-linked user actionTaken dedupe, races, and write failures remain Firestore-only and atomic", async () => {
  const prepare = () => { const store = db(); seedAdmin(store); store.data.set("machine_reports/item", {status: "new", targetType: "user", targetUserId: "target-user"}); store.data.set("users/target-user", {accountStatus: "active", email: "private@example.invalid"}); return store; }; const input = actionRequest("report", "item", "restricted", "550e8400-e29b-41d4-a716-4466554400b8"); const replay = prepare(); await applyModerationQueueActionForCaller(replay, caller, input); await applyModerationQueueActionForCaller(replay, caller, input); assert.equal(count(replay, "moderation_private_audit/"), 1); assert.equal(count(replay, "request_deduplication/"), 1); const race = prepare(); race.beforeTransaction = () => race.data.set("machine_reports/item", {status: "resolved", resolution: "actionTaken", targetType: "user", targetUserId: "target-user"}); await assert.rejects(() => applyModerationQueueActionForCaller(race, caller, input)); assert.equal(race.data.get("users/target-user")?.accountStatus, "active"); for (const failedPath of ["users/target-user", "machine_reports/item", "moderation_private_audit/", "request_deduplication/"]) { const failure = prepare(); failure.fail.add(failedPath); await assert.rejects(() => applyModerationQueueActionForCaller(failure, caller, {...input, requestId: input.requestId.slice(0, -1) + "0"})); assert.equal(failure.data.get("users/target-user")?.accountStatus, "active"); assert.equal(failure.data.get("users/target-user")?.email, "private@example.invalid"); assert.equal(failure.data.get("machine_reports/item")?.status, "new"); assert.equal(count(failure, "moderation_private_audit/"), 0); assert.equal(count(failure, "request_deduplication/"), 0); }
});

test("queue-linked photo hidden actionTaken updates public/private records without Storage for report and correction", async () => {
  for (const [sourceType, collection, itemId, requestId] of [["report", "machine_reports", "photo-report", "550e8400-e29b-41d4-a716-4466554400b9"], ["correction", "machine_corrections", "photo-correction", "550e8400-e29b-41d4-a716-4466554400ba"]] as const) { const store = db(); seedAdmin(store); store.data.set(`${collection}/${itemId}`, {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1", category: "other", createdAt: 1}); store.data.set("vending_machines/machine-1/photos/photo-1", {status: "active", createdAt: 1}); store.data.set("vending_machine_private/machine-1/photos/photo-1", {uploadedBy: "private", recognition: "private"}); const result = await applyModerationQueueActionForCaller(store, caller, actionRequest(sourceType, itemId, "hidden", requestId)); const publicPhoto = store.data.get("vending_machines/machine-1/photos/photo-1")!; const privatePhoto = store.data.get("vending_machine_private/machine-1/photos/photo-1")!; assert.equal(result.targetType, "photo"); assert.equal(result.photoId, "photo-1"); assert.equal(publicPhoto.status, "inactive"); assert.equal(privatePhoto.moderationStatus, "hidden"); assert.equal(privatePhoto.uploadedBy, "private"); assert.equal(store.data.get(`${collection}/${itemId}`)?.resolution, "actionTaken"); for (const key of ["uploadedBy", "actorUid", "moderatorUid", "storagePath", "queue", "deletionCompletedAt"]) assert.equal(key in publicPhoto, false); assert.equal(JSON.stringify(result).includes("private"), false); }
});

test("queue-linked photo hidden rejects invalid target, lifecycle, and public/private state without resolving queue", async () => {
  const cases: ReadonlyArray<readonly [string, Data, Data | undefined, Data | undefined, string]> = [["wrong-type", {status: "new", targetType: "machine", machineId: "machine-1"}, {status: "active"}, {uploadedBy: "private"}, "550e8400-e29b-41d4-a716-4466554400bb"], ["missing-photo", {status: "new", targetType: "photo", machineId: "machine-1"}, {status: "active"}, {uploadedBy: "private"}, "550e8400-e29b-41d4-a716-4466554400bc"], ["pending", {status: "resolutionPending", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}, {status: "active"}, {uploadedBy: "private"}, "550e8400-e29b-41d4-a716-4466554400bd"], ["resolved", {status: "resolved", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}, {status: "active"}, {uploadedBy: "private"}, "550e8400-e29b-41d4-a716-4466554400be"], ["public-missing", {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}, undefined, {uploadedBy: "private"}, "550e8400-e29b-41d4-a716-4466554400bf"], ["public-inactive", {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}, {status: "inactive"}, {uploadedBy: "private"}, "550e8400-e29b-41d4-a716-4466554400c0"], ["private-missing", {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}, {status: "active"}, undefined, "550e8400-e29b-41d4-a716-4466554400c1"], ["private-inconsistent", {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}, {status: "active"}, {uploadedBy: "private", moderationStatus: "deleted"}, "550e8400-e29b-41d4-a716-4466554400c2"]]; for (const [itemId, queue, publicPhoto, privatePhoto, requestId] of cases) { const store = db(); seedAdmin(store); store.data.set(`machine_reports/${itemId}`, queue); if (publicPhoto) store.data.set("vending_machines/machine-1/photos/photo-1", publicPhoto); if (privatePhoto) store.data.set("vending_machine_private/machine-1/photos/photo-1", privatePhoto); await assert.rejects(() => applyModerationQueueActionForCaller(store, caller, actionRequest("report", itemId, "hidden", requestId))); assert.equal(store.data.get(`machine_reports/${itemId}`)?.status, queue.status); assert.equal(count(store, "moderation_private_audit/"), 0); assert.equal(count(store, "request_deduplication/"), 0); }
});

test("queue-linked photo hidden dedupe, races, and write failures are atomic without Storage", async () => {
  const prepare = () => { const store = db(); seedAdmin(store); store.data.set("machine_reports/item", {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}); store.data.set("vending_machines/machine-1/photos/photo-1", {status: "active"}); store.data.set("vending_machine_private/machine-1/photos/photo-1", {uploadedBy: "private"}); return store; }; const input = actionRequest("report", "item", "hidden", "550e8400-e29b-41d4-a716-4466554400c3"); const replay = prepare(); await applyModerationQueueActionForCaller(replay, caller, input); await applyModerationQueueActionForCaller(replay, caller, input); assert.equal(count(replay, "moderation_private_audit/"), 1); assert.equal(count(replay, "request_deduplication/"), 1); const race = prepare(); race.beforeTransaction = () => race.data.set("machine_reports/item", {status: "resolved", resolution: "actionTaken", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}); await assert.rejects(() => applyModerationQueueActionForCaller(race, caller, input)); assert.equal(race.data.get("vending_machines/machine-1/photos/photo-1")?.status, "active"); for (const failedPath of ["vending_machines/machine-1/photos/photo-1", "vending_machine_private/machine-1/photos/photo-1", "machine_reports/item", "moderation_private_audit/", "request_deduplication/"]) { const failure = prepare(); failure.fail.add(failedPath); await assert.rejects(() => applyModerationQueueActionForCaller(failure, caller, {...input, requestId: input.requestId.slice(0, -1) + "0"})); assert.equal(failure.data.get("vending_machines/machine-1/photos/photo-1")?.status, "active"); assert.equal(failure.data.get("vending_machine_private/machine-1/photos/photo-1")?.moderationStatus, undefined); assert.equal(failure.data.get("machine_reports/item")?.status, "new"); assert.equal(count(failure, "moderation_private_audit/"), 0); assert.equal(count(failure, "request_deduplication/"), 0); }
});

test("queue-linked photo deleted completes report and correction through pending Storage and finalize", async () => {
  for (const [sourceType, collection, itemId, requestId] of [["report", "machine_reports", "photo-delete-report", "550e8400-e29b-41d4-a716-4466554400d1"], ["correction", "machine_corrections", "photo-delete-correction", "550e8400-e29b-41d4-a716-4466554400d2"]] as const) {
    const store = db(); seedAdmin(store); store.data.set(`${collection}/${itemId}`, {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1", createdAt: 1}); store.data.set("vending_machines/machine-1/photos/photo-1", {status: "active"}); store.data.set("vending_machine_private/machine-1/photos/photo-1", {uploadedBy: "private"}); const bucket = new FakeBucket();
    const result = await applyModerationQueueActionForCaller(store, caller, actionRequest(sourceType, itemId, "deleted", requestId), bucket);
    assert.equal(result.status, "resolved"); assert.equal(result.resolution, "actionTaken"); assert.equal(store.data.get("vending_machines/machine-1/photos/photo-1")?.status, "inactive"); assert.equal(store.data.get("vending_machine_private/machine-1/photos/photo-1")?.moderationStatus, "deleted"); assert.equal(store.data.get(`${collection}/${itemId}`)?.status, "resolved"); assert.equal(store.data.get(`${collection}/${itemId}`)?.resolution, "actionTaken"); assert.deepEqual(bucket.deleted, ["vending_machines/machine-1/photo-1/original.jpg"]); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); const page = await listModerationQueueForCaller(createFirestoreModerationReadStore(store), caller, {limit: 10}); assert.deepEqual(page.items, []); const publicPhoto = store.data.get("vending_machines/machine-1/photos/photo-1")!; for (const key of ["uploadedBy", "actorUid", "moderatorUid", "storagePath", "deletionPending", "deletionCompletedAt", "queue"]) assert.equal(key in publicPhoto, false);
  }
});

test("queue-linked photo deleted retains pending state across Storage and finalize failures then safely retries", async () => {
  const store = db(); seedAdmin(store); store.data.set("machine_reports/item", {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1", createdAt: 1}); store.data.set("vending_machines/machine-1/photos/photo-1", {status: "active"}); store.data.set("vending_machine_private/machine-1/photos/photo-1", {uploadedBy: "private"}); const input = actionRequest("report", "item", "deleted", "550e8400-e29b-41d4-a716-4466554400d3"); const bucket = new FakeBucket(); bucket.failure = new Error("storage unavailable"); await assert.rejects(() => applyModerationQueueActionForCaller(store, caller, input, bucket)); assert.equal(store.data.get("machine_reports/item")?.status, "resolutionPending"); assert.equal(store.data.get("vending_machine_private/machine-1/photos/photo-1")?.moderationStatus, "deletionPending"); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1);
  store.data.set("users/admin-2", {accountStatus: "active"}); await assert.rejects(() => applyModerationQueueActionForCaller(store, {uid: "admin-2", customClaims: {admin: true}}, {...input, requestId: "550e8400-e29b-41d4-a716-4466554400d5"}, bucket)); assert.equal(store.data.get("machine_reports/item")?.status, "resolutionPending"); bucket.failure = {code: "storage/object-not-found"}; await applyModerationQueueActionForCaller(store, caller, input, bucket); assert.equal(store.data.get("machine_reports/item")?.status, "resolved"); assert.equal(store.data.get("vending_machine_private/machine-1/photos/photo-1")?.moderationStatus, "deleted"); assert.equal(count(store, "moderation_private_audit/"), 1); assert.equal(count(store, "request_deduplication/"), 1); const deletes = bucket.deleted.length; await applyModerationQueueActionForCaller(store, caller, input, bucket); assert.equal(bucket.deleted.length, deletes); assert.equal(count(store, "moderation_private_audit/"), 1);
});

test("queue-linked photo deleted rolls back phase 1 and preserves pending state when finalize validation or stage fails", async () => {
  const prepare = () => { const store = db(); seedAdmin(store); store.data.set("machine_reports/item", {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}); store.data.set("vending_machines/machine-1/photos/photo-1", {status: "active"}); store.data.set("vending_machine_private/machine-1/photos/photo-1", {uploadedBy: "private"}); return store; };
  const input = actionRequest("report", "item", "deleted", "550e8400-e29b-41d4-a716-4466554400d4");
  for (const failedPath of ["vending_machines/machine-1/photos/photo-1", "vending_machine_private/machine-1/photos/photo-1", "machine_reports/item", "moderation_private_audit/", "request_deduplication/"]) { const store = prepare(); const bucket = new FakeBucket(); store.fail.add(failedPath); await assert.rejects(() => applyModerationQueueActionForCaller(store, caller, input, bucket)); assert.equal(bucket.deleted.length, 0); assert.equal(store.data.get("machine_reports/item")?.status, "new"); assert.equal(store.data.get("vending_machines/machine-1/photos/photo-1")?.status, "active"); assert.equal(store.data.get("vending_machine_private/machine-1/photos/photo-1")?.moderationStatus, undefined); }
  const validateFailure = prepare(); const validateBucket = new FakeBucket(); validateBucket.onDelete = () => validateFailure.data.set("machine_reports/item", {status: "new", targetType: "photo", machineId: "machine-1", photoId: "photo-1"}); await assert.rejects(() => applyModerationQueueActionForCaller(validateFailure, caller, input, validateBucket)); assert.equal(validateFailure.data.get("machine_reports/item")?.status, "new"); assert.equal(validateFailure.data.get("vending_machine_private/machine-1/photos/photo-1")?.moderationStatus, "deletionPending");
  const stageFailure = prepare(); const stageBucket = new FakeBucket(); stageBucket.onDelete = () => stageFailure.fail.add("machine_reports/item"); await assert.rejects(() => applyModerationQueueActionForCaller(stageFailure, caller, input, stageBucket)); assert.equal(stageFailure.data.get("machine_reports/item")?.status, "resolutionPending"); assert.equal(stageFailure.data.get("vending_machine_private/machine-1/photos/photo-1")?.moderationStatus, "deletionPending"); stageFailure.fail.clear(); stageBucket.onDelete = undefined; stageBucket.failure = {code: "storage/object-not-found"}; await applyModerationQueueActionForCaller(stageFailure, caller, input, stageBucket); assert.equal(stageFailure.data.get("machine_reports/item")?.status, "resolved"); assert.equal(stageFailure.data.get("vending_machine_private/machine-1/photos/photo-1")?.moderationStatus, "deleted"); assert.equal(count(stageFailure, "moderation_private_audit/"), 1); assert.equal(count(stageFailure, "request_deduplication/"), 1);
});
