import type {ModerationTarget} from "./moderation_core";

export type ModerationQueueSourceType = "report" | "correction";
export type ModerationQueueStatus = "new" | "inReview" | "resolutionPending" | "resolved";
export type ModerationResolution = "actionTaken" | "noAction" | "rejected";
export interface ModerationQueueRef { readonly sourceType: ModerationQueueSourceType; readonly itemId: string; }
export interface StoredQueueTarget { readonly targetType: "machine" | "photo" | "product" | "text" | "user"; readonly machineId?: string; readonly photoId?: string | null; readonly productId?: string | null; readonly targetUserId?: string | null; }
export interface QueueTransitionPlan { readonly allowed: boolean; readonly nextStatus: ModerationQueueStatus | null; readonly resolution: ModerationResolution | null; }

export function parseModerationQueueRef(value: unknown): ModerationQueueRef { if (!isRecord(value) || (value.sourceType !== "report" && value.sourceType !== "correction") || typeof value.itemId !== "string" || value.itemId.trim().length === 0 || Object.keys(value).some((key) => key !== "sourceType" && key !== "itemId")) throw new ModerationQueueValidationError("invalid-queue-reference"); return {sourceType: value.sourceType, itemId: value.itemId.trim()}; }
export function targetFromStoredQueueItem(value: StoredQueueTarget): ModerationTarget { if (value.targetType === "machine" || value.targetType === "text") return {targetType: "machine", machineId: required(value.machineId)}; if (value.targetType === "photo" && value.photoId) return {targetType: "photo", machineId: required(value.machineId), photoId: required(value.photoId)}; if (value.targetType === "product" && value.productId) return {targetType: "product", machineId: required(value.machineId), productId: required(value.productId)}; if (value.targetType === "user") return {targetType: "user", targetUserId: required(value.targetUserId)}; throw new ModerationQueueValidationError("invalid-queue-target"); }
export function validateQueueTarget(stored: StoredQueueTarget, requested: ModerationTarget): void { const target = targetFromStoredQueueItem(stored); if (JSON.stringify(target) !== JSON.stringify(requested)) throw new ModerationQueueValidationError("queue-target-mismatch"); }
export function planQueueTransition(current: ModerationQueueStatus, operation: "inReview" | "actionTaken" | "noAction" | "rejected" | "photoFinalize"): QueueTransitionPlan { if (current === "resolved") return {allowed: false, nextStatus: null, resolution: null}; if (operation === "inReview") return current === "new" ? {allowed: true, nextStatus: "inReview", resolution: null} : {allowed: false, nextStatus: null, resolution: null}; if (operation === "photoFinalize") return current === "resolutionPending" ? {allowed: true, nextStatus: "resolved", resolution: "actionTaken"} : {allowed: false, nextStatus: null, resolution: null}; if (operation === "actionTaken") return current === "new" || current === "inReview" ? {allowed: true, nextStatus: "resolved", resolution: "actionTaken"} : {allowed: false, nextStatus: null, resolution: null}; return current === "new" || current === "inReview" ? {allowed: true, nextStatus: "resolved", resolution: operation} : {allowed: false, nextStatus: null, resolution: null}; }
export function planQueueLinkedModeration(status: ModerationQueueStatus, isPhotoDelete: boolean): QueueTransitionPlan { if (isPhotoDelete) return (status === "new" || status === "inReview") ? {allowed: true, nextStatus: "resolutionPending", resolution: null} : {allowed: false, nextStatus: null, resolution: null}; return planQueueTransition(status, "actionTaken"); }
function required(value: unknown): string { if (typeof value !== "string" || value.trim().length === 0) throw new ModerationQueueValidationError("invalid-queue-target"); return value.trim(); }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
export class ModerationQueueValidationError extends Error { constructor(readonly code: string) { super(code); } }
