class PrefectureMaster {
  final String name;
  final String region;

  const PrefectureMaster({
    required this.name,
    required this.region,
  });

  static const List<PrefectureMaster> values = <PrefectureMaster>[
    PrefectureMaster(name: '北海道', region: '北海道'),
    PrefectureMaster(name: '青森県', region: '東北'),
    PrefectureMaster(name: '岩手県', region: '東北'),
    PrefectureMaster(name: '宮城県', region: '東北'),
    PrefectureMaster(name: '秋田県', region: '東北'),
    PrefectureMaster(name: '山形県', region: '東北'),
    PrefectureMaster(name: '福島県', region: '東北'),
    PrefectureMaster(name: '茨城県', region: '関東'),
    PrefectureMaster(name: '栃木県', region: '関東'),
    PrefectureMaster(name: '群馬県', region: '関東'),
    PrefectureMaster(name: '埼玉県', region: '関東'),
    PrefectureMaster(name: '千葉県', region: '関東'),
    PrefectureMaster(name: '東京都', region: '関東'),
    PrefectureMaster(name: '神奈川県', region: '関東'),
    PrefectureMaster(name: '新潟県', region: '中部'),
    PrefectureMaster(name: '富山県', region: '中部'),
    PrefectureMaster(name: '石川県', region: '中部'),
    PrefectureMaster(name: '福井県', region: '中部'),
    PrefectureMaster(name: '山梨県', region: '中部'),
    PrefectureMaster(name: '長野県', region: '中部'),
    PrefectureMaster(name: '岐阜県', region: '中部'),
    PrefectureMaster(name: '静岡県', region: '中部'),
    PrefectureMaster(name: '愛知県', region: '中部'),
    PrefectureMaster(name: '三重県', region: '近畿'),
    PrefectureMaster(name: '滋賀県', region: '近畿'),
    PrefectureMaster(name: '京都府', region: '近畿'),
    PrefectureMaster(name: '大阪府', region: '近畿'),
    PrefectureMaster(name: '兵庫県', region: '近畿'),
    PrefectureMaster(name: '奈良県', region: '近畿'),
    PrefectureMaster(name: '和歌山県', region: '近畿'),
    PrefectureMaster(name: '鳥取県', region: '中国'),
    PrefectureMaster(name: '島根県', region: '中国'),
    PrefectureMaster(name: '岡山県', region: '中国'),
    PrefectureMaster(name: '広島県', region: '中国'),
    PrefectureMaster(name: '山口県', region: '中国'),
    PrefectureMaster(name: '徳島県', region: '四国'),
    PrefectureMaster(name: '香川県', region: '四国'),
    PrefectureMaster(name: '愛媛県', region: '四国'),
    PrefectureMaster(name: '高知県', region: '四国'),
    PrefectureMaster(name: '福岡県', region: '九州'),
    PrefectureMaster(name: '佐賀県', region: '九州'),
    PrefectureMaster(name: '長崎県', region: '九州'),
    PrefectureMaster(name: '熊本県', region: '九州'),
    PrefectureMaster(name: '大分県', region: '九州'),
    PrefectureMaster(name: '宮崎県', region: '九州'),
    PrefectureMaster(name: '鹿児島県', region: '九州'),
    PrefectureMaster(name: '沖縄県', region: '沖縄'),
  ];
}