// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDynS4pySOCAOrKlWeB56ZxQtdZxJ4i5Vc',
    appId: '1:215928026767:web:27968608b66758921462fa',
    messagingSenderId: '215928026767',
    projectId: 'jihanki-navi',
    authDomain: 'jihanki-navi.firebaseapp.com',
    storageBucket: 'jihanki-navi.firebasestorage.app',
    measurementId: 'G-S895CRYGQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkzYQKlhcEFHqk7iOjne5gnOsv0NQNav4',
    appId: '1:215928026767:android:692c7cc8e9f985a61462fa',
    messagingSenderId: '215928026767',
    projectId: 'jihanki-navi',
    storageBucket: 'jihanki-navi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE4HSupnUZiTiUpVWdwEqjule1ZdAj3UY',
    appId: '1:215928026767:ios:5e5149d8c29f59f21462fa',
    messagingSenderId: '215928026767',
    projectId: 'jihanki-navi',
    storageBucket: 'jihanki-navi.firebasestorage.app',
    iosBundleId: 'com.example.vendingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE4HSupnUZiTiUpVWdwEqjule1ZdAj3UY',
    appId: '1:215928026767:ios:5e5149d8c29f59f21462fa',
    messagingSenderId: '215928026767',
    projectId: 'jihanki-navi',
    storageBucket: 'jihanki-navi.firebasestorage.app',
    iosBundleId: 'com.example.vendingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDynS4pySOCAOrKlWeB56ZxQtdZxJ4i5Vc',
    appId: '1:215928026767:web:17d7fd83e54a8b861462fa',
    messagingSenderId: '215928026767',
    projectId: 'jihanki-navi',
    authDomain: 'jihanki-navi.firebaseapp.com',
    storageBucket: 'jihanki-navi.firebasestorage.app',
    measurementId: 'G-7WBTDZYLLG',
  );
}
